### ISSUE TITLE
Default route name conversion does not follow Symfony defaults

### ISSUE THREAD

**Issue by sandermarechal** [sensiolabs/SensioFrameworkExtraBundle#218]
Just an annoying little thing I ran across. The conversion from CamelCase to under_score does not seem to follow Symfony defaults when converting the bundle name for the default routes. For example the `My\TinyCmsBundle` is converted by Symfony itself to `my_tiny_cms`  (for e.g. config variables and other places where the underscored name is used). The default route name generated by the `@Route` annotation for this bundle uses `my_tinycms` instead of `my_tiny_cms`.

It's a small thing but quite annoying, seeing in how many places in Symfony an underscored bundle name is used (config variables, routes, service names, etcetera).

I don't know if this is fixable without breaking BC through... :-/

**Comment by peto85** [comment]
Thanks for your comment, I was having to explicitly set @route names before reading it.

**Comment by fabpot** [comment]
Possible to fix it in 4.0. Anyone willing to make a PR. Should be an easy pick.

**Comment by fabpot** [comment]
I'm closing as a won't fix as after some investigation, fixing it means overriding the parent method from Symfony altogether and so have a different algorithm between Symfony and this bundle. Not worth it if you ask me.
