### ISSUE TITLE
[ParamConverterListener] Interferes with passage of objects to twig Render(Controller())

### ISSUE THREAD

**Issue by ErichHartmann** [sensiolabs/SensioFrameworkExtraBundle#229]
As discussed in [syfmony issue #7124](https://github.com/symfony/symfony/issues/7124#issuecomment-20632698), if I use symfony2's new twig render() function for internal requests to embed a controller response like below code:

```php
{# src/Acme/ArticleBundle/Resources/views/Article/displayArticle.html.twig #}
...
{% for entity in entities %}
    {{ render(controller('AcmeArticleBundle:Comment:Show', {'entity': entity})) }}
{% endfor %}
```
The code adds redundant DB queries to retrieve each Comment entity in entities despite passing the fully populated object to the below controller.

```php
// src/Acme/ArticleBundle/Controller/CommentController.php

public function showAction(Comment $entity)
{
    if (!$entity instanceof Comment) {
        throw $this->InvalidArgumentException('Action requires a Comment Entity.');
    }

    $deleteForm = $this->createDeleteForm($entity->getId());
    $editForm = $this->createEditForm($entity->getId());

    return $this->render('@AcmeArticleBundle/Comment/show.html.twig',
        array(
            'entity'      => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView()
        )
    );
}
```
It appears to me (via profiler/timeline) that the Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener (as invoked by the kernel.controller event) is re-instigating doctrine queries to the already passed and populated entity. When the kernel.controller is done, the re-queried entity is passed to the controller called in the render function.

If true, this fault causes a redundant DB query for every entity in entities.

I note that the above code is not using any annotations (like template or route) and that the showAction has no defined route. I wanted it only accessible internally for the testbed.

**Comment by fabpot** [comment]
Closing this old ticket without any activities
