### ISSUE TITLE
[Cache] Incorrect mapped documentation?

### ISSUE THREAD

**Issue by stefantalen** [sensiolabs/SensioFrameworkExtraBundle#256]
Not sure how the connection with the Symfony website is made from the docs but when I browse the `@Cache` [documentation](http://symfony.com/doc/2.3/bundles/SensioFrameworkExtraBundle/annotations/cache.html) for version 2.3 it includes the **lastModified** option.

If I'm not mistaken that option was made available as of SensioFrameworkExtraBundle 3.0 which requires Symfony 2.4.

The [documentation file](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v2.3.4/Resources/doc/annotations/cache.rst) in the v2.3.4 tag also does not include this option.

**Comment by javiereguiluz** [comment]
We can close this issue as **fixed** because the reported `lastModified` option no longer appears in Symfony 2.3 documentation.
