### ISSUE TITLE
Confusing doc versions

### ISSUE THREAD

**Issue by WouterJ** [sensiolabs/SensioFrameworkExtraBundle#270]
When reading the doc about this bundle on symfony.com, the version switchers shows `2.4` (Symfony's latest stable release). This confuses people, as they are reading the `3.0` docs of this bundle.

The best solution would be to change the version switcher on symfony.com (that'll immediately solve the version issues with the CMF).

Another option will be to add the version at the top of the docs, or to add a caution on the index page.

This issue was previously reported in https://github.com/symfony/symfony-docs/issues/3484

**Comment by javiereguiluz** [comment]
@WouterJ I think we can safely close this issue because the switcher now correctly shows the version of the bundle.
