### ISSUE TITLE
@Security – compare record $id and login user id to edit owner records

### ISSUE THREAD

**Issue by kvaje** [sensiolabs/SensioFrameworkExtraBundle#294]
I would like to introduce security into my app so I decided to use SensioFrameworkExtraBundle. In some actions I need that user can edit only their own records.

Is it possible to make security in annotations and check if edited record ID is the same as login user id (for User controler for example).

How can I make something similar in SensioFrameworkExtraBundle
 
    /**
     * @Security("has_role('ROLE_USER_EDIT_OWNER')  and  ($id == app.user.id)")
     */ 
    public function editAction(Request $request, $id)
    {
         ……
    }

Is this possible or I missed at all?

**Comment by Koc** [comment]
@kvaje http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html#usage (starting from "The expression has access to the following variables: ...")

```php
    /**
     * @ParamConverter("callback", class="MetalCallbacksBundle:Callback")
     * @Security("has_role('ROLE_SUPPLIER') and has_role('ROLE_CONFIRMED_EMAIL') and (callback.getCompany().getId() == user.getCompany().getId())")
     */
    public function processCallbackAction(Callback $callback)
    {

```
