### ISSUE TITLE
Add support for different naming strategies in template annotations names

### ISSUE THREAD

**Issue by iltar** [sensiolabs/SensioFrameworkExtraBundle#303]
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Templating/TemplateGuesser.php#L58-L60

Regarding conventions: "Use alphanumeric characters and underscores for file names"
https://github.com/symfony/symfony-docs/issues/2515#issuecomment-20284485
http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

Examples:
https://github.com/symfony/FrameworkBundle/tree/master/Resources/views/Form
https://github.com/symfony/TwigBridge/tree/master/Resources/views/Form
https://github.com/symfony/WebProfilerBundle/tree/master/Resources/views/Profiler

@Template() with default value generation, works against the convention as mentioned. My proposal is to add support for different naming strategies, camel casing could be the default to prevent BC breaks but an option should be present to convert it to underscores, preferably bundle specific.

**Comment by OHB** [comment]
:+1:

**Comment by ewgRa** [comment]
Read this issue and summarize this, #213 and my #341 maybe it is good idea to have Template(guesser=... ? Or "format=lowercase,namespace"?

**Comment by fabpot** [comment]
see #507
