### ISSUE TITLE
Add extra variables to @Security ExpressionLanguage

### ISSUE THREAD

**Issue by sandermarechal** [sensiolabs/SensioFrameworkExtraBundle#305]
I would like to have some way to add extra variables to the ExpressionLanguage in the @Security annotation.

Use case: I am integrating OAuth2. #285 allows me to add a new function, for example:

```
@Security('has_scope("scope1 scope2")')
```

But I need to have my OAuth2 service available as a variable in the ExpressionLanguage or I can't evaluate my new function.
Currently there is no way to add extra variables. The SecurityListener offers no such functionality and the SecurityListener class is hard-coded in config/security.xml instead of being provided by a parameter.

**Comment by ryall** [comment]
I did this by overriding the listener with a compiler pass and injecting via request attributes (as these are merged into the security vars). It's a bit hacky but it's the simplest way I could find until this feature is added.

https://gist.github.com/ryall/b2835915696ecabf2f049fcdbc30bea9

**Comment by fabpot** [comment]
You can do so via request attributes.
