### ISSUE TITLE
ParamConverter supporting BOTH ODM and ORM

### ISSUE THREAD

**Issue by nick4fake** [sensiolabs/SensioFrameworkExtraBundle#308]
AFAIK, now it is only possible to use ODM *instead* of ORM.

But in finance projects we have both of them (ORM for transactional queries). But now ODM should be fetched by hand, as mostly ParamConverter is used for ORM now.

Is there any workaround?

**Comment by fabpot** [comment]
Closing as I'm not using the ODM (and apparently, not a lot of people are asking for its support here). If anyone is willing to provide support for it, I would be more than happy to have a look at the pull request.
