### ISSUE TITLE
[SecurityListener] Make exception message changeable

### ISSUE THREAD

**Issue by drgomesp** [sensiolabs/SensioFrameworkExtraBundle#309]
The [SecurityListener](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/SecurityListener.php) has an exception message when the [access is denied](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/SecurityListener.php#L57).

It would be nice to be able to change that message to make it translatable across the application. Currently, I can't translate it because of the expression language that goes inside of it.

Any suggestions?

**Comment by fabpot** [comment]
Closing in favor of the discussion in #332
