### ISSUE TITLE
Too weak typehint at ParamConverterManager->applyConverter

### ISSUE THREAD

**Issue by nicoschoenmaker** [sensiolabs/SensioFrameworkExtraBundle#315]
A small case of [Duck typing](http://en.wikipedia.org/wiki/Duck_typing) in the SensioFrameworkExtraBundle. `$configuration` is typehinted as `Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationInterface`, yet `getName()` and `getClass()` only exist on `Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter`.

```
    protected function applyConverter(Request $request, ConfigurationInterface $configuration)
    {
        $value     = $request->attributes->get($configuration->getName());
        $className = $configuration->getClass();
        // More stuff
    }
```

Current situation when you inject a ConfigurationInterface: Fatal Error.
Possible solutions: Stricter typehint, instanceof check, ...?

**Comment by frak** [comment]
Which of the solutions is preferred?  Doing an instanceof seems crude but adding methods to the interface will create other work.

**Comment by nicoschoenmaker** [comment]
Adding methods to an interface is backwards incompatible.

Changing the typehint is also backwards incompatible.

So I'm afraid that an instanceof (while ugly) might be your best bet.

**Comment by Jean85** [comment]
Since this has a label for (potentially) 4.0, a BC would not be off the table. Should we go for a stricter typehint?

**Comment by nicoschoenmaker** [comment]
Stricter typehint would be most correct & expressive of course.

`ParamConverter` is the only subclass that implements the called methods.

Looking at it a bit closer, I'm not sure why this method has been chosen to be protected, perhaps it should simply be private?

**Comment by frak** [comment]
Do we know for sure that this stage that the configuration will be for a ParamConverter or can other types of configuration be passed in? If other types are possible then I would opt for type checking rather than hinting so that errors are not thrown.

**Comment by fabpot** [comment]
In `ParamConverterManager`, `$configurations` passed to `apply()` comes from `ParamConverterListener::onKernelController()`. There, there are extracted from `$request->attributes->get('_converters')`, which contains all configuration for which `getAliasName()` returns `converters`. Only `ParamConverter does that`. So, it's safe to change the `ConfigurationInterface` type-hint on `ParamConverterManager::applyConverter()` to `ParamConverter`. Let's do it on master as we might break edge cases, but that should really never happen.

```diff
diff --git a/Request/ParamConverter/ParamConverterManager.php b/Request/ParamConverter/ParamConverterManager.php
index d2ddeb2..2dbed08 100644
--- a/Request/ParamConverter/ParamConverterManager.php
+++ b/Request/ParamConverter/ParamConverterManager.php
@@ -12,7 +12,7 @@
 namespace Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter;

 use Symfony\Component\HttpFoundation\Request;
-use Sensio\Bundle\FrameworkExtraBundle\Configuration\ConfigurationInterface;
+use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

 /**
  * Managers converters.
@@ -52,7 +52,7 @@ class ParamConverterManager
     /**
      * Applies converter on request based on the given configuration.
      */
-    private function applyConverter(Request $request, ConfigurationInterface $configuration)
+    private function applyConverter(Request $request, ParamConverter $configuration)
     {
         $value = $request->attributes->get($configuration->getName());
         $className = $configuration->getClass();
```
