### ISSUE TITLE
[@Security] allow class-scope ACL in is_granted Annotation

### ISSUE THREAD

**Issue by RubenKruiswijk** [sensiolabs/SensioFrameworkExtraBundle#335]
When using class-scope aces in Symfony2 ACL, it would be useful to be able to use them in annotations. 

When listing Post objects for example, you might want to check if a user has LIST permissions on the Post class as an instantiated object is not available. In an action you could do that like this:

```php
$securityContext = $this->get('security.context');
$securityContext->isGranted('LIST', new ObjectIdentity('class', '\\Entity\\Post')));
```

How do I do that using Annotation, if even possible?
Using ``@Security`` annotation, it could look like this:
```php
/**
  * @Security("is_granted('LIST', '\\Entity\\Post')")
  * @return Response
  */
public function allPostsAction()
{
```

**Comment by JHGitty** [comment]
:+1:

**Comment by jakzal** [comment]
It might be something more suitable for JMSSecurityExtraBundle, which already provides more [advanced ways of role checking](http://jmsyst.com/bundles/JMSSecurityExtraBundle/master/annotations#secure).

**Comment by iltar** [comment]
@jakzal I disagree. This kind of basic functionality is something `@Security` could support. I like to avoid dependencies on JMS by all cost. 

This functionality can be added through the Expressions:
```php
/**
  * @Security("is_granted('LIST', class_identity('\\Entity\\Post'))")
  * @return Response
  */
public function allPostsAction()
{
```

The ACL component (bundle in the future) could add the option to expose a bit of code to transform the above to:
```php
$authorizer->isGranted('LIST', new ObjectIdentity('class', '\\Entity\\Post')));
```

**Comment by JHGitty** [comment]
Agree to @iltar - I really need this! :+1:

**Comment by fabpot** [comment]
Closing as ACLs are not part of Symfony Core anymore.
