### ISSUE TITLE
BC break Cache annotation

### ISSUE THREAD

**Issue by Thorry84** [sensiolabs/SensioFrameworkExtraBundle#345]
In 3.0.5 the following change was made with regards to the Cache annotation to fix the response being public or private. https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/4c2e3e5d03857cc13fcf2a0bced34c587f59677e

However when the public key isn't added it always sets the response as being private adding the cache-control: private. Before this change was made it would not set the cache-control header at all, which is the desired behavior (I think).

To fix this I think the code should check whether the value was set in the first place and not add a header when it wasn't set.

**Comment by fabpot** [comment]
@Thorry84 Can you propose a pull request to fix this regression? Thanks.

**Comment by Thorry84** [comment]
Done!
