### ISSUE TITLE
[DX] Look for templates in `app/Resources/views` before `AppBundle/Resources/views`

### ISSUE THREAD

**Issue by parhamdoustdar** [sensiolabs/SensioFrameworkExtraBundle#351]
As views are moving from inside `AppBundle/Resources/Views` out into `app/Resources/Views`, the `@template` annotation must check that directory too by default, to keep the behavior of retrieving the view for a particular controller without having to specify it every time.

**Comment by JHGitty** [comment]
How to fix this? I like to move all my templates to app/Resources/views/ for best practice.

**Comment by JHGitty** [comment]
Best practice is to NOT use ``@Template()``
http://symfony.com/doc/master/best_practices/controllers.html#template-configuration

But I think this should be fixed for people who like to use it.

**Comment by iltar** [comment]
I like to use it to avoid depending on the `EngineInterface` (Controller as a Service) or any templating at all. I want to stop treating my App split from AppKernel and AppBundle and integrate my bundle into the App itself. I think it would be really nice if this would work in case this is still a valid issue.

**Comment by xabbuh** [comment]
The guessing is done in https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Templating/TemplateGuesser.php and you will have to find a way to tell the guesser not to refer to the bundle here.

**Comment by mcwebb** [comment]
+1 to the issue, but I think it would be a big BC break to first look in `app/Resources/views` by default.
I think the only option would be to add an option to the annotation.

**Comment by JHGitty** [comment]
Can we do a BC break for a version for Symfony 3.0+ ?

**Comment by iltar** [comment]
This is not part of Symfony, so in theory it could be done for version 4 of this bundle. Would it really be a BC break to look in that location first?

**Comment by parhamdoustdar** [comment]
I would think since applications made with the current version of this 
bundle don't have such a directory, it would not be a breaking change. 
It's not like you're changing an existing behavior; you're adding a new 
behavior.

**Comment by mcwebb** [comment]
There is a BC break though it's small: someone could have two templates named exactly the same in their `/src/AppBundle/Resources/views/` dir and also in the `/app/Resources/views/` dir; this change would suddenly load the template in `/app/` which could be totally unrelated.

But you're right, putting the change into a major version (or maybe even a minor version) would probably be fine.

**Comment by fabpot** [comment]
Closing as version 4 does not support the Templating component anymore, just plain-old Twig.
