### ISSUE TITLE
integrate helper to modify DI configuration

### ISSUE THREAD

**Issue by dbu** [sensiolabs/SensioFrameworkExtraBundle#354]
@xabbuh built a tool to adjust the DI configuration: https://github.com/xabbuh/DIConfigurationBundle
would it make sense to integrate this in the SensioFrameworkExtraBundle?

**Comment by timglabisch** [comment]
:-1: cant get the usecase

**Comment by dbu** [comment]
it would basically be providing a class for the compiler pass to replace the class of a service with a different one. in the cases where the construction does not change (e.g. extended the class to overwrite some public/protected methods) this saves a couple of lines of boilerplate code that otherwise would need to be shipped with everything that replaces a class in the DI container.

**Comment by slde-flash** [comment]
why not providing a special compiler pass for this? i dislike creating more and more ways to solve the same problem.

**Comment by dbu** [comment]
that is what i meant. no need to have anything fancy, just a compiler class that accepts a service name and a target class and changes the service definition to use that class instead. i think its a pretty common case and now that classes are not parameters anymore it would be boilerplate to add that compiler pass class everywhere.

**Comment by fabpot** [comment]
I agree with @dbu. :+1:

**Comment by dbu** [comment]
@xabbuh do you want to do a pull request then to contribute that compiler pass to this bundle?

**Comment by xabbuh** [comment]
I'll have a look into this next week.

**Comment by dbu** [comment]
@xabbuh did that happen? is the feature freeze for symfony 3 also affecting this bundle?

**Comment by fabpot** [comment]
Closing as I don't think this should be part of this bundle (which is mainly about providing annotations on controllers).
