### ISSUE TITLE
Wrong parameter conversion with multiple @Route annotations

### ISSUE THREAD

**Issue by King2500** [sensiolabs/SensioFrameworkExtraBundle#355]
I encountered a problem, when you have multiple `@Route` annotations and one of them uses a field name from the entity of the other route:

``` php
/**
 * Displays a form to create a new or edit an existing Post entity.
 *
 * @Route("/new/{title}", name="admin_post_new")
 * @Route("/edit/{id}", requirements={"id" = "\d+"}, name="admin_post_edit")
 */
public function editAction(Request $request, $title = null, Post $post = null)
{
    if ($post === null) {
        $post = new Post();
        $post->setTitle($title);
    } 
    // ...
```

![image](https://cloud.githubusercontent.com/assets/4896363/7687110/27c4c81c-fd9b-11e4-8b27-4a72649a63a9.png)

When the `admin_post_edit` route gets called, the `title` attribute is in the request attributes as well (intended behavior of the Routing component?), which leads to the ParamConverter using the `title` field to search for the entity.

![image](https://cloud.githubusercontent.com/assets/4896363/7687116/39696956-fd9b-11e4-9374-15e9e93b1e88.png)

The standard `@ParamConverter` annotation didn't help:

```
@ParamConverter("post", class="AppBundle:Post")
```

... unless I explictly exclude the `title`:

```
@ParamConverter("post", class="AppBundle:Post", options={"exclude"={"title"}})
```

I had this problem in current project, and so I reproduced it in a symfony-demo fork:
https://github.com/King2500/symfony-demo/tree/bug_paramconverter

I made a fix for this (including tests), but I'm not sure if it's the correct solution:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/master...King2500:fix-multi-route-parameters

If it's fine, I can create a pull-request.
Let me know, if you have any questions.

**Comment by King2500** [comment]
@fabpot @beberlei 

Can someone review this?

**Comment by Glideh** [comment]
`ParamConverter` is a great tool that I'll use extensively.
However I'm encountering the same behavior.
I issued an [SO question](http://stackoverflow.com/q/37455733/305189) just before finding this one.
I also suspect it's not working as expected.

**Comment by Tobion** [comment]
> When the admin_post_edit route gets called, the title attribute is in the request attributes as well 

This has been fixed with https://github.com/symfony/symfony/pull/21379
So that should also fix the param converter to not use the title field.
