### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by mmucklo** [sensiolabs/SensioFrameworkExtraBundle#356]
Could  a LICENSE file be placed in the root of this repo and merged into the branches?

**Comment by xabbuh** [comment]
There is a license file under [Resources/meta/LICENSE](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Resources/meta/LICENSE).

**Comment by mmucklo** [comment]
Ok Thanks, searched but didn't immediately find it.

**Comment by skreutzer** [comment]
Please mention this path at least in the README.md file, that would be very helpful. Thanks!
