### ISSUE TITLE
[DX] Add csrf_provider in @Security annotation ?

### ISSUE THREAD

**Issue by Alsatian67** [sensiolabs/SensioFrameworkExtraBundle#362]
Could be like :
```
/*
*@Security("isCsrfTokenValid('secret',csrf)")
*@Route("/message/{id}/remove/{csrf}", name="message_remove")
*/
public function removeMessageAction(Message $message, $csrf){
[...]
}
```

**Comment by Alsatian67** [comment]
Any feedback ?
Should I make a PR or this function is not intented from FrameworkExtraBundle ?

**Comment by jvasseur** [comment]
I don't think adding this to the security annotation is a good idea. If you do it like this and the token expire, the user will get an access denied exception that doesn't correspond the the actual error.
