### ISSUE TITLE
Simplest way to disable the DoctrineParamConverter

### ISSUE THREAD

**Issue by hanneskaeufler** [sensiolabs/SensioFrameworkExtraBundle#365]
Hi,

the `DoctrineParamConverter` is a cool thing for simple apps, but for my app it´s not enough to simply go and fetch an entity via doctrine. Whatever the case, it would be super cool to disable the DoctrineConverter as it automagically jumps into place and bypasses some of my own ParamConverters if I´m not super careful.

How can I disable the DoctrineConverter in the most simple way? I figure removing the definition in a compiler pass would work but then I would also need to find the method call to the manager because of the container tag. Is there a better way?

**Comment by xabbuh** [comment]
The only easy way currently is to [disable all converters](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html#configuration).

**Comment by iltar** [comment]
I was actually thinking of this in the morning. I need additional checks for every entity I fetch, like: "is the current user allowed to see it?"

I think it would be an idea to make this converter optional by configuring it to be on/off.

**Comment by fabpot** [comment]
#511 does that
