### ISSUE TITLE
[DX] Renaming Route Annotation to Controller

### ISSUE THREAD

**Issue by iltar** [sensiolabs/SensioFrameworkExtraBundle#367]
I'm still trying to find a solution for the miss-usage of `@Route` on the controller level. In my opinion it shouldn't be an `@Route` Annotation but something else as it's confusing. What about renaming it to `@Controller`?

_Old situation_

``` php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * @Route(service="app.controller.some-controller")
 */
class SomeController
{
    /**
     * @Route("/some-route/", name="app.some-route")
     */
    public function firstLoginAction(ClientInterface $client)
    {}
}
```

_New situation_

``` php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Controller;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Controller("app.controller.some-controller")
 */
class SomeController
{
    /**
     * @Route("/some-route/", name="app.some-route")
     */
    public function firstLoginAction(ClientInterface $client)
    {}
}
```

In case you do want to provide a prefix for your controller routes:

``` php
/**
 * @Controller("app.controller.some-controller", prefix="/my-prefix")
 */
```

It's pretty easy to write a BC layer for this solution. If people like this solution, I can write a PR.

**Comment by fabpot** [comment]
I'm confused. Are you suggesting to replace `@Route` only for controller as a service set in the main class phpdoc?

**Comment by iltar** [comment]
Yes, that's pretty much it. It will also make it possible to [remove this logic](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/8cf9ba588534a3f910907c3093db1cfc9419a50f/Routing/AnnotatedRouteControllerLoader.php#L54-L56). Right now you have 2 Route annotations, of which for methods there's no difference except that it can trigger and exception if configured incorrectly. This would bring it down to 1 Route annotation and 1 Controller annotation to which you can give a prefix in your controller as done in [the yaml variant](http://symfony.com/doc/current/book/routing.html#prefixing-imported-routes). Right now that option is just the first argument. Personally I use the service option far more than the value/path option, which is also the main reason I use the `@Route` from the extra bundle instead of core.

**Comment by kralos** [comment]
Hrm, if this ends up happening I should probably follow suit with #403 I think `@Controller` is more logical.

**Comment by fabpot** [comment]
LGTM. @iltar Can you submit a PR on master for that change? Thanks.

**Comment by iltar** [comment]
I'm not so sure the Route annotation is needed anymore. If you register the controller under the FQCN, the controller will be available as such with `:actionName` afaik. I'll test this later to see if this is true for 3.3+

**Comment by fabpot** [comment]
@iltar any news, can we close?

**Comment by iltar** [comment]
Just tested it and I can register controllers with their FQCN as service id and it will work without annotation on the class and I haven't used the Route annotation from this bundle for the route definitions either (just the core one).

So in theory the annotation could be removed altogether, but that opens one edge case. If you wish to do a subrequest, you will have to use the FQCN now.

```twig
{{ render(controller("App\\Controller\\DashboardController:test")) }}
vs
{{ render(controller("app.controller.dashboard:test")) }}
```
The above issue can easily be solved with:
```yml
services:
    app.controller.dashboard:
        alias: App\Controller\DashboardController
```

So my conclusion is that in theory, we no longer need the specialized route annotation. The diff (in just the loader) would be something like:

```diff
diff --git a/Routing/AnnotatedRouteControllerLoader.php b/Routing/AnnotatedRouteControllerLoader.php
index 2a2489d..9d66cf0 100644
--- a/Routing/AnnotatedRouteControllerLoader.php
+++ b/Routing/AnnotatedRouteControllerLoader.php
@@ -13,7 +13,6 @@ namespace Sensio\Bundle\FrameworkExtraBundle\Routing;
 
 use Symfony\Component\Routing\Loader\AnnotationClassLoader;
 use Symfony\Component\Routing\Route;
-use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route as FrameworkExtraBundleRoute;
 use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
 
 /**
@@ -36,11 +35,7 @@ class AnnotatedRouteControllerLoader extends AnnotationClassLoader
      */
     protected function configureRoute(Route $route, \ReflectionClass $class, \ReflectionMethod $method, $annot)
     {
-        // controller
-        $classAnnot = $this->reader->getClassAnnotation($class, $this->routeAnnotationClass);
-        if ($classAnnot instanceof FrameworkExtraBundleRoute && $service = $classAnnot->getService()) {
-            $route->setDefault('_controller', $service.':'.$method->getName());
-        } elseif ('__invoke' === $method->getName()) {
+        if ('__invoke' === $method->getName()) {
             $route->setDefault('_controller', $class->getName());
         } else {
             $route->setDefault('_controller', $class->getName().'::'.$method->getName());
@@ -50,8 +45,6 @@ class AnnotatedRouteControllerLoader extends AnnotationClassLoader
         foreach ($this->reader->getMethodAnnotations($method) as $configuration) {
             if ($configuration instanceof Method) {
                 $route->setMethods(implode('|', $configuration->getMethods()));
-            } elseif ($configuration instanceof FrameworkExtraBundleRoute && $configuration->getService()) {
-                throw new \LogicException('The service option can only be specified at class level.');
             }
         }
     }
```
