### ISSUE TITLE
New @CsrfProtected

### ISSUE THREAD

**Issue by romaricdrigon** [sensiolabs/SensioFrameworkExtraBundle#375]
Hi,

Currently CSRF protection is under-looked in many SF applications, typically with exposed GET requests (deleting an object... pretty much any admin or admin generator!).
That code is required to check a token from a GET parameter:

``` php
        if (!$this->get('security.csrf.token_manager')->isTokenValid(new CsrfToken('intention', $request->query->get('token')))) {
            throw $this->createAccessDeniedException('Invalid CSRF token');
        }
```

I feel like it could be made simpler:

``` php
/**
 * @CsrfProtected("intention")
 */
```

This looks like a small gain, but it make things more "automatic" as security annotation. Pretty much some DX.
I wanted to propose the idea here before working on a PR.

**Comment by issei-m** [comment]
:+1: 
In addition, It'd be more better to get extendability (meaning any HTTP methods/token name are allowed to use), I think.

**Comment by timglabisch** [comment]
:+1:

**Comment by romqin** [comment]
I like the idea. :+1:

**Comment by hhamon** [comment]
Very nice and usefull!

I would name it `CsrfProtection`.

**Comment by SofHad** [comment]
:+1:

**Comment by Alsatian67** [comment]
See #362

**Comment by romaricdrigon** [comment]
Hello @Alsatian67 ,
Then another Exception than AccessDenied should be used, which one though?

**Comment by apfelbox** [comment]
As a side note: meanwhile the main framework has added a helper method to the base controller: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php#L436.

```php
$this->isCsrfTokenValid('intention', $request->query->get('token'));
```

So the code without the annotation is a little bit shorter.

**Comment by Alsatian67** [comment]
@romaricdrigon it was just to say that I already proposed some kind of feature ;)

But I think you idea to create another annotation is better than my (provide a helper in the security annotation).

I don't know what to use instead of AccessDenied (for me it doesn't hurt and I don't like to give too much informations).

**Comment by jameshalsall** [comment]
`Symfony\Component\HttpKernel\Exception\BadRequestHttpException`?

**Comment by fabpot** [comment]
Closing as there is a PR about this.
