### ISSUE TITLE
Don't catch exception from action when use @Template

### ISSUE THREAD

**Issue by sergiors** [sensiolabs/SensioFrameworkExtraBundle#383]
Hi, I have the following code
```php
/**
 * @Route("/{id}", requirements={"id" = "\d+"}, name="classroom_inscription_index")
 * @Template("@Classroom/Inscription/index.html.twig")
 */
public function indexAction(Application $app, $id)
{
    $inscription = $app['orm']
        ->getRepository(Inscription::class)
        ->findOneBy([
            'id' => $id,
            'user' => $app->user()
        ]);

    if (!$inscription) {
        throw new NotFoundHttpException();
    }
    // ....
}
```

But, when occurs the render, the exception `NotFoundHttpException` it's not catch, just the next, thrown by template engine, so, I don't get capture the correct  exception..

I do a way to don't render when occurs an exception before template engine render, see the link: https://github.com/sergiors/sensio-framework-extra-service-provider/blob/master/src/EventListener/TemplateListener.php#L41

But, it's the best way?

Someone have the even error?

**Comment by sergiors** [comment]
@xabbuh ping

**Comment by xabbuh** [comment]
I am not sure I understand your issue. Which exception do you mean is caught instead?

**Comment by sergiors** [comment]
When I throw an exception in controller action, the TemplateListener runs normally, throwing new exceptions from template engine, like undefined variable.

**Comment by xabbuh** [comment]
I don't see why that should happen. It will return in https://github.com/sergiors/sensio-framework-extra-service-provider/blob/master/src/EventListener/TemplateListener.php#L97-L99 then, won't it?

**Comment by sergiors** [comment]
Yes, to avoid render of template engine.

**Comment by xabbuh** [comment]
Well, but where should the exception getting thrown then? It seems that providing a small example (best would be a modified fork of the Standard Edition) would make this more obvious.
