### ISSUE TITLE
@Template does not work when there are no variables

### ISSUE THREAD

**Issue by mediamonks-robert** [sensiolabs/SensioFrameworkExtraBundle#385]
When using @Template it is apparently required to set any variable or otherwise it will silently ignore and throw an exception about no response being returned.

```php
class DefaultController extends Controller
{
    /**
     * @Template
     */
    public function indexAction()
    {
    }
}
```

Expected result: template MyBundle:Default:index.html.twig will be rendered
Actual result: an exception is thrown: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?"

The code responsible:

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/TemplateListener.php#L98

It is not clear from documentation that having a variable is actually a requirement, I would expect it to work without too. My preference is that a template is being rendered anyway without this current checks on template vars, if this is not possible it would be good to put it in documentation.

**Comment by iltar** [comment]
This case is only triggered if you return null _and_ have no arguments. I can make a fix for this as my intention was to work on this either way.

**Comment by jakzal** [comment]
You need to at least return an empty array.

**Comment by iltar** [comment]
I'm working on a PR and take this into consideration (I need to refactor quite a bit in there).
