### ISSUE TITLE
 Annotating controller as a service/dependency component

### ISSUE THREAD

**Issue by chinmayshah24** [sensiolabs/SensioFrameworkExtraBundle#386]
From
https://github.com/symfony/symfony/issues/16626

So currently we can use `@Route` to specify a controller as a service

http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#controller-as-service

Shouldn't we have a separate annotation for it?

Instead of doing it this way:
```
/**
 * @Route(service="my_post_controller_service")
 */
class PostController
{
    // ...
}
```
How about this:

```
/**
 * @Controller("my_post_controller_service")
 */
class PostController
{
    // ...
}
```

Like in Java/Spring MVC we have `@Controller` , `@Service`, `@Component`, `@Resource` for Autowiring "beans".

**Comment by iltar** [comment]
@chinmayshah24 see https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/367
