### ISSUE TITLE
never true in detect is optional in param converter

### ISSUE THREAD

**Issue by hash60** [sensiolabs/SensioFrameworkExtraBundle#410]
this line 
`if (null === $request->attributes->get($name, false)) {`
at framework-extra-bundle Request ParamConverter DoctrineParamConverter 
 public function apply
this condition never returns true
but 
`if (false === $request->attributes->get($name, false)) {`
when name is null returns true
and with this change optional paramConverter now works property

**Comment by hosseinashrafzadeh** [comment]
this is better
`if (null === $request->attributes->get($name, null)) {`

**Comment by fabpot** [comment]
fixed in bd7e329
