### ISSUE TITLE
Variables in SecurityListener::getVariables can conflict with @Security

### ISSUE THREAD

**Issue by taylankasap** [sensiolabs/SensioFrameworkExtraBundle#411]
I don't have time to dig into it more right now but this doesn't work:

```
/**
 * Displays a form to edit an existing User entity.
 *
 * @Route("/{id}/edit", name="tenant_user_edit")
 * @Template
 * @Security("is_granted('edit', user)")
 * @Breadcrumb("Edit User")
 */
public function editAction(Request $request, User $user)
{
    // Irrelevant stuff
}
```

while this _does_ work as expected:

```
/**
 * Displays a form to edit an existing User entity.
 *
 * @Route("/{id}/edit", name="tenant_user_edit")
 * @Template
 * @Security("is_granted('edit', tenantUser)")
 * @Breadcrumb("Edit User")
 */
public function editAction(Request $request, User $tenantUser)
{
    // Irrelevant stuff
}
```

Only difference is one uses `user` and the other one uses `tenantUser`. I left other annotations intact on purpose.

I think it's related to `$variables` defined in `Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::getVariables`

**Comment by xabbuh** [comment]
As you can see [in the documentation](http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/security.html#usage) there are few variables that are pass automatically to the context of the expression being evaluated (`user` being one of them). So you will need to ensure in your code not to use the same identifiers for custom request attributes if you want to be able to use them in the expression.

**Comment by taylankasap** [comment]
Sorry, I didn't see that.

Then maybe it can throw an error or warning. Because that will probably never be intentional. (I mean using `user` and `$user` at the same time.)

**Comment by xabbuh** [comment]
Logging a warning might be a good idea (I didn't check if that's actually possible given how the code currently works).

**Comment by iltar** [comment]
In my opinion it would be a good idea to prefix those variables, like `security.user`, `security.token` or something similar.

**Comment by hhamon** [comment]
Why not prefixing them with an underscore to remain consistent with Symfony and its built-in special variables?

**Comment by iltar** [comment]
An underscore is also a prefix so if that works, it has my vote. This way they don't pollute the userland variables.

**Comment by jeffclemens** [comment]
+1.  This tripped me up too.  

It adds to the confusion that is_granted('edit', user) works as expected in Twig templates.

**Comment by fabpot** [comment]
Adding an underscore is fine by me. Anyone willing to make a PR for master? Adding a note in CHANGELOG about this BC break would be nice (and docs update).

**Comment by hhamon** [comment]
@fabpot I can work on it!

Which of the following prefixes do you think are better:

Underscore Prefix Style
------------------------

```
@Security("_user.username == 'system'")
```

Custom Prefix Style
--------------------

```
@Security("security.user.username == 'system'")
```

Twig Global Vars Style
-----------------------

```
@Security("app.user.username == 'system'")
```

**Comment by fabpot** [comment]
I think that only the underscore notation can really "fix" the issue of possible conflicts.

**Comment by hhamon** [comment]
Okay let's go the for the underscore style then.

**Comment by hhamon** [comment]
Prefixing the variables will require to also update a Symfony Security core class:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/ExpressionLanguageProvider.php

Or overriding all these functions in the SensioFrameworkExtraBundle Expression language (see `Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage`).

**Comment by fabpot** [comment]
@hhamon It means that we cannot do it at all. So, throwing an exception is probably the best option.

**Comment by fabpot** [comment]
see #504
