### ISSUE TITLE
Routes not imported from Controller dir if controllers are encrypted

### ISSUE THREAD

**Issue by razvan-malos** [sensiolabs/SensioFrameworkExtraBundle#413]
If the project files are encrypted with ZendGuard, AnnotationDirectoryLoader / AnnotationFileLoader cannot import routes because \Symfony\Component\Routing\Loader\AnnotationFileLoader::findClass reads the controller file as text

`$tokens = token_get_all(file_get_contents($file));`

I did this to solve my problem:
`$filePathAbs = $file->getRealPath();`
`$filePathRel = str_replace(APPLICATION_DIR .'/src/', '', $filePathAbs);`
`$class = str_replace(DIRECTORY_SEPARATOR, '\\', str_replace('.php','',$filePathRel));`

where APPLICATION_DIR is defined as `dirname(__DIR__)` in app.php/app_dev.php but i'm not sure this is the best solution.

Also, the annotations don't work like :
`use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;`
`...`
`/** @Route("/", name="home") */`

In order to work, the FQ class name should be used :
`
/** @Sensio\Bundle\FrameworkExtraBundle\Configuration\Route("/", name="home") */
`

Tank you !

**Comment by iltar** [comment]
If this is an issue, you should probably open it here: https://github.com/doctrine/annotations/. I'm not sure why you would want to "encrypt" your code though.

**Comment by fabpot** [comment]
Closing as this is not related to this repo.
