### ISSUE TITLE
Route annotations not imported from a Trait

### ISSUE THREAD

**Issue by Pierstoval** [sensiolabs/SensioFrameworkExtraBundle#415]
Suppose an `AdminController`, and some behaviors in Traits.

If you create `MyBehaviorControllerTrait` and add this, for example:

```php
<?php

use use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

trait MyBehaviorControllerTrait
{
    /**
     * @Route("/my-behavior")
     */
    public function behaviorAction()
    {
        return new Response('My behavior');
    }
}
``` 

If this trait is imported by *any* controller, the new `Route` annotation will never be imported :confused:

**Comment by iltar** [comment]
As far as I know the loader reads the class and this annotation is not in the class. By adding this feature it will become nearly impossible to fix all cases. The config reader is in the symfony repository though, not here.

The only case where I can think of where this makes sense, is by prefixing all controllers and re-using actions. But why would you want to duplicate logic? Why not simply redirect them to the same action?

**Comment by Pierstoval** [comment]
When you create CRUD controllers, or Api/Web services that inherit from other services, it could be interesting to use behaviors instead of inheritance.
 
Of course what you propose about prefixing the controller (I'll add that one should not "name" the actions in traits to avoid too many naming logic) is important because else there would be too much conflicts.
 
But for now there is only one way of creating "automatic routes behaviors" : create the method in a trait/abstract class and call it from the controller (which is not 100% of what I'm asking for with this issue). Or create a service, but this goes out of the "Controller" concept then :confused: .
 
In terms of concepts/design patterns, I don't know if controller behaviors is a good idea though (even if Symfony1 and CakePHP used "Components" for this kind of case).

**Comment by iltar** [comment]
If you want to re-use code, inject services, easier and better solution, also keeps your controllers thin.

**Comment by HeahDude** [comment]
Can be closed as fixed by https://github.com/symfony/symfony/pull/18907.

**Comment by fabpot** [comment]
Thanks @HeahDude
