### ISSUE TITLE
Template::setOwner() must be of the type array, object given

### ISSUE THREAD

**Issue by benr77** [sensiolabs/SensioFrameworkExtraBundle#421]
SensioFrameworkExtraBundle 3.0.16 with Symfony 2.8.8.

In the production environment, I get the error below when I define caching using the annotation:

`@Cache(lastModified="post.getModified()", ETag="'Post' ~ post.getId() ~ post.getModified().getTimestamp()", public=true)`

And the error is:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Sensio\Bundle\FrameworkExtraBundle\Configuration\Template::setOwner() must be of the type array, object given, called in /app/cache/prod/classes.php on line 8208 and defined" at /vendor/sensio/framework-extra-bundle/Configuration/Template.php line 172`

If I remove the annotation the error goes away.

The error does not occur in the dev environment.

Any ideas?

Thanks

**Comment by benr77** [comment]
This issue appears to completely disappear when reverting to SensioFrameworkExtraBundle 3.0.12

**Comment by raphaabreu** [comment]
I believe that this is related with I have been seeing on #420.

**Comment by NadaBen** [comment]
Hello, did you find a solution for this issue ?

**Comment by benr77** [comment]
I haven't had time to dig any deeper - all I know is that with 3.0.12 it works ok, so I've locked that as my dependency for the time being.

**Comment by NadaBen** [comment]
Okey i will try with 3.0.12 thank you ..

**Comment by snroki** [comment]
Hi, got the same issue with FOSRestBundle when using the @View annotation along with the @Cache (with lastModified or ETag values) and i can't use the 3.0.12 tag because FOSRestBundle 2.0 branch as a minimum of 3.0.13 SensioFrameworkExtraBundle. 
Do you think a fix can be choose ? (Either the check to set the controller only if it's an array or the stopPropagation). Thanks !

**Comment by NadaBen** [comment]
same issue as you @snroki  i'm using FOSRestBundle 2.0 , I can't use the 3.0.12 verion of SensioFrameworkExtraBundle..; i did not find any solution .. :'( still have the same error
