### ISSUE TITLE
Symfony 3 deprecation warning

### ISSUE THREAD

**Issue by wikimatze** [sensiolabs/SensioFrameworkExtraBundle#426]
Hi,

I'm right in the middle of updating my Symfony projects, running the `deprecation-detector.phar` on the master of this projects gives me the following message:

```sh
| 1 | Using deprecated interface Symfony\Component\Security\Core\SecurityContextInterface | 39   | since version 2.6, to be removed in 3.0. |
```

Are there any plans to get refactor this code?

Cheers,

Matthias

**Comment by weaverryan** [comment]
See #431 :)

**Comment by fabpot** [comment]
Even the current code works fine. What you refer to is a layer of BC that needs to be maintained for older versions of Symfony. But if you are using a newer one, you will never hit this part of the code. So, no issue here.

**Comment by wikimatze** [comment]
Thanks for the clarification.
