### ISSUE TITLE
[DX] Display _template and _cache values inside the Request profiler

### ISSUE THREAD

**Issue by GromNaN** [sensiolabs/SensioFrameworkExtraBundle#429]
When using the `@Template`or `@Cache` annotations, the profiler displays only the class of the Request attributes. 

![profiler](https://cloud.githubusercontent.com/assets/400034/18477326/95450244-79cd-11e6-9eb3-8abd8d3df59f.png)

It would be nice if the profiler could display the actual configuration. Making a `dump` of each request attribute.

**Comment by fabpot** [comment]
agreed

**Comment by Koc** [comment]
looks like this issue Symfony-related and was fixed by https://github.com/symfony/symfony/pull/19614

**Comment by GromNaN** [comment]
Thanks.
