### ISSUE TITLE
ParamConverter should use type hinting also with auto_convert=false

### ISSUE THREAD

**Issue by akomm** [sensiolabs/SensioFrameworkExtraBundle#434]
Having `request.auto_convert: false`, it feels very redundant to write this:

```php
    /**
     * @ParamConverter("data", class="AppBundle\DTO\DataObject")
     */
    public function __invoke(DataObject $data)
    {
    }
```
Would it not make sense if it would work like that:
```php
    /**
     * @ParamConverter("data")
     */
    public function __invoke(DataObject $data)
    {
    }
```

You should still be able to provide `class` via option.

**Comment by fabpot** [comment]
It's even better than that. As explained in the docs, if you are type-hinting, no need to use the `@ParamConverter` annotation.

**Comment by akomm** [comment]
@fabpot When I set `auto_convert: false` as said both in title and post, it does not.
