### ISSUE TITLE
Incompatibility with "grouped use" PHP7 feature

### ISSUE THREAD

**Issue by tristanbes** [sensiolabs/SensioFrameworkExtraBundle#442]
Hello,

When using `group use` from **PHP7** it ends up with an error (`"sensio/framework-extra-bundle": "^3.0.2"`)

`[Semantical Error] The annotation "@Route" in class ...Controller was never imported. Did you maybe forget to add a "use" statement for this annotation?`

To reproduce, just replace your use with 
```php
<?php
// namespace ..;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\{Route, Template, Security, ParamConverter};
```

**Comment by pyrech** [comment]
Looks like it's more a problem with doctrine/annotations - see [https://github.com/doctrine/annotations/pull/69](https://github.com/doctrine/annotations/pull/69) but not any news since many months :disappointed:

**Comment by fabpot** [comment]
Closing as unfortunately, it must be fixed upstream.
