### ISSUE TITLE
Allow to use ::class in @ParamConverter

### ISSUE THREAD

**Issue by n-sviridenko** [sensiolabs/SensioFrameworkExtraBundle#448]
Hello!

When I try to set the class using `::class`:

```
use App\Model\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @ParamConverter("user", class=User::class)
 */
```

I have the following error:

```
PHP Warning:  Invalid argument supplied for foreach() in src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php on line 123
```

This error means that annotation loader couldn't parse the comment. But when I'm changing `User::class` to `"App\Model\User"` it works.

Informations:

```
PHP 7.0.14-1~dotdeb+8.1 (cli) ( NTS )

doctrine/annotations@v1.3.0
sensio/framework-extra-bundle@v3.0.16
```

**Comment by jakzal** [comment]
I don't think this is technically possible. For doctrine's annotation parser the value of class attribute is just a string. Afaik the parser doesn't know anything about classes imported in the context where annotation is used.

The warning doesn't seem to be coming from the paramconverter annotation. Can you please paste the whole docblock?

**Comment by fabpot** [comment]
Closing as there is no more feedback. Anyway, use `::class` in a annotation is not supported and probably cannot be.

**Comment by tristanbes** [comment]
Well it is possible for ORM mapping, @fabpot // @jakzal , but maybe it's not the same context for this annotation ?

```
    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="site")
     */
    protected $locations;
```

**Comment by fabpot** [comment]
Ah, great, that means that the Doctrine Annotation lib supports it. @tristanbes Do you want to have a look if that's possible to support it in other contexts?

**Comment by tristanbes** [comment]
I'll try to take a look next week and let you know what I've found here.

**Comment by jvasseur** [comment]
@fabpot it already works with the parameter converter, the doctrine annotation is doing the conversion from `::class` to the FQCN making it work out of the box.

The error in the original bug report must come from somewhere else.

**Comment by fabpot** [comment]
Ok, that's great news then. Closing again :)
