### ISSUE TITLE
[DoctrineParamConverter] is not generating HttpNotFoundException when the param was not found

### ISSUE THREAD

**Issue by nmacherey** [sensiolabs/SensioFrameworkExtraBundle#458]
Previously to that version the DoctrineParamConverter was generating an HttpNotFoundException when the param was not found.

A change in bde7329 revision breaks this down.
previously lines 49 to 51 were:

        if (null === $request->attributes->get($name, false)) {
            $configuration->setIsOptional(true);
        }
but now it is

        if (null === $request->attributes->get($name)) {
            $configuration->setIsOptional(true);
        }

Best regards.

**Comment by nicosomb** [comment]
Hi there. 

Same here, 3.0.20 changed this behavior.

**Comment by xabbuh** [comment]
Does 3.0.21 work for you?

**Comment by nmacherey** [comment]
Yes perfect !
