### ISSUE TITLE
Rename ETag to Etag?

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioFrameworkExtraBundle#461]
In https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/Configuration/Cache.php we define `getETag()` and `setETag()` ... and that's why you must use `ETag='...'` in `@Cache()`.

However, in Symfony we use `getEtag()` and `setEtag()` (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L903)

Lastly, the HTTP header is `ETag`.

Should we fix this inconsistency?

**Comment by fabpot** [comment]
So, you would rename to `Etag` in the bundle? That sounds good to me for version 4.0. Anyone willing to submit a PR with a note in the CHANGELOG and updated docs?
