### ISSUE TITLE
ParamConverter not working with newest version

### ISSUE THREAD

**Issue by wtk13** [sensiolabs/SensioFrameworkExtraBundle#468]
I had custom ParamConverter, with version 3.0.24 it stop working. I had ith with priority = 0 and it worked before default converter.

My config:

`app.survey_converter:
 class: AppBundle\ParamConverter\SurveyConverter
arguments: ['@doctrine', '@security.token_storage']
tags:
            - { name: request.param_converter}
`

**Comment by fabpot** [comment]
It was a release issue. I've just tagged 3.0.25.
