### ISSUE TITLE
v3.0.24 was tagged from master

### ISSUE THREAD

**Issue by maff** [sensiolabs/SensioFrameworkExtraBundle#469]
The recently released version v3.0.24 seems to have been released from master, including breaking changes from the upcoming v4. Could you please check the release?

Thanks!

**Comment by bitgandtter** [comment]
Please correct this having a lot of issues with new version

**Comment by IrcDirk** [comment]
Same problem here, had to downgrade to 3.0.23.

**Comment by fabpot** [comment]
Sorry for about that. Not sure how that happened. Fixed now with 2.0.25.

**Comment by maff** [comment]
Thanks for the quick fix!
