### ISSUE TITLE
TemplateGuesser class, method access changed from protected to private

### ISSUE THREAD

**Issue by bmxmiko** [sensiolabs/SensioFrameworkExtraBundle#470]
Why did you converted protected method into private in TemplateGuesser class ? We are extending this class and using method "getBundleForClass". What we can do ? Also in changelog we can see version "4.0", but there is no such version (latest 3.0.24).

**Comment by IrcDirk** [comment]
Downgrade to 3.0.23. Worked for me.

**Comment by xabbuh** [comment]
see #469, for now you should just exclude 3.0.24 from the versions you accept

**Comment by bmxmiko** [comment]
Yes, I downgraded too and working, but I need to know if this is mistake or not :) Thanks for replies.

**Comment by IrcDirk** [comment]
I think they will make fix for this, as this should not be in 3.x version.

**Comment by fabpot** [comment]
2.0.25 is out now. Sorry for the mess.
