### ISSUE TITLE
Form ParamConverter

### ISSUE THREAD

**Issue by Aliance** [sensiolabs/SensioFrameworkExtraBundle#477]
I have a working implementation of form ParamConverter, which can be used like so:
```php
    /**
     * @ParamConverter("entity", options={"form": "FormFQCN"})
     */
    public function someAction(Entity $entity)
    {
        // ...
    }
```

I can share it by making a PR if there is okay adding new ParamConverter.

**Comment by iltar** [comment]
Do you have some more information of what it does?

**Comment by Aliance** [comment]
You have some Symfony form:
```php
class EntityFormType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults([
            'data_class' => Entity::class,
        ]);
    }
}
```

Instead of writing:
```php
    public function someAction(Request $request)
    {
        $form = $this->get('form.factory')->createNamed('', EntityFormType::class);
        $form->handleRequest($request);
        $entity = $form->getData();
    }
```

You can write
```php
    /**
     * @ParamConverter("entity", options={"form": "\Name\Space\EntityFormType"})
     */
    public function someAction(Entity $entity)
    {
        // ...
    }
```

**Comment by iltar** [comment]
So what if you don't have a named form, which is the most common case? What if you don't bind your entity to forms?

**Comment by Aliance** [comment]
Just do not use this param converter if you have not named/binded form types.

**Comment by iltar** [comment]
Then I don't think this parameter converter is generic enough to add to this bundle.

**Comment by fabpot** [comment]
Ok, closing as it does not seem to be generic enough for inclusion in this bundle.
