### ISSUE TITLE
Multiple prefixes for the same Controller

### ISSUE THREAD

**Issue by raimonbosch** [sensiolabs/SensioFrameworkExtraBundle#479]
Hi all,

We are trying to modify our routing.xml to have something like this:

```
<import resource="@MyWebBundle/Controller/MyProduct"
            type="annotation"
            prefix="/us/myproduct" />

 <import resource="@MyWebBundle/Controller/MyProduct"
            type="annotation"
            prefix="/uk/myproduct" />
```
but when I run php app/console router:debug I only see the last route.

Is there any way to have both prefixes pointing to the same controller?

Thanks in advance,

**Comment by apfelbox** [comment]
One way to do that would be to add a placeholder and restrict it with requirements:

```xml
<import resource="@MyWebBundle/Controller/MyProduct"
            type="annotation"
            prefix="/{country}/myproduct">
    <requirement key="country">us|uk</requirement>
</import>
```

Not sure wether there is way to do it with static prefixes.

**Comment by fabpot** [comment]
@apfelbox is right, closing.
