### ISSUE TITLE
Wrong Twig namespace for templates with Symfony Flex

### ISSUE THREAD

**Issue by vladimmi** [sensiolabs/SensioFrameworkExtraBundle#480]
I'm experimenting with Symfony Flex and Symfony 3.3.0-RC1. Found a problem with template paths when using `@Template()` annotation.

All I've installed to create skeleton project:
- `"symfony/flex": "^1.0@dev"`
- `"symfony/framework-bundle": "3.3.*"`
- `"symfony/twig-bundle": "3.3.*"`
- `"sensio/framework-extra-bundle": "^4.0@dev"`

Configuration done by Flex, yaml files created and everything looks working.

I have `App\Controller\IndexController::indexAction` in `src/Controller/IndexController.php`. Action returns array and is annotated with `@Template()`. Corresponding template exists as `templates/index/index.html.twig`. But request results in exception: `Unable to find template "@Framework/Index/index.html.twig" (looked into: /path/to/project/vendor/symfony/framework-bundle/Resources/views).`

For some reason default template namespace is set to `@Framework` - is it some misconfiguration or something wrong with not-yet-released code?

**Comment by fabpot** [comment]
Fixed in 5e6808f
