### ISSUE TITLE
@security not working

### ISSUE THREAD

**Issue by DavidVerdier** [sensiolabs/SensioFrameworkExtraBundle#484]
I just noticed that security annotation no longer works do you know why?

```php
<?php

namespace XX\PDFBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use XX\BouteilleBundle\Entity\Bouteille;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/pdf")
 */
class PDFController extends Controller
{
    /**
     * @Route("/bouteille/{id}/{token}", defaults={"token" = null})", name="xx_pdf_cerfa_bouteille"))
     * @ParamConverter("bouteille")
     * @Security("is_granted('canShowCerfaBouteille', bouteille)")
     */
    public function cerfaBouteilleAction(Bouteille $bouteille, $token)
    {
        
        $test =  $this->get('security.authorization_checker')->isGranted('canShowCerfaBouteille', $bouteille);
        
        die(var_dump($test)); // return bool(false)
    }
```

**Comment by DavidVerdier** [comment]
Ok,
This work
   * @Security("is_granted('canShowCerfaBouteille', bouteille)")
   * @Route("/bouteille/{id}/{token}", defaults={"token" = null})", name="fi_pdf_cerfa_bouteille"))
   * @ParamConverter("bouteille")

Does not work:
   * @Route("/bouteille/{id}/{token}", defaults={"token" = null})", name="fi_pdf_cerfa_bouteille"))
   * @Security("is_granted('canShowCerfaBouteille', bouteille)")
   * @ParamConverter("bouteille")

Does not work:
   * @Route("/bouteille/{id}/{token}", defaults={"token" = null})", name="fi_pdf_cerfa_bouteille"))
   * @ParamConverter("bouteille")
   * @Security("is_granted('canShowCerfaBouteille', bouteille)")

**Comment by jakzal** [comment]
Your route annotation is closed too early. It should be something like:

```
@Route("/bouteille/{id}/{token}", defaults={"token" = null}, name="xx_pdf_cerfa_bouteille")
```

Unfortunately the parser cannot deal with such of problems.

Anyway, nothing to do here.
