### ISSUE TITLE
StreamedResponse does not work

### ISSUE THREAD

**Issue by slootjes** [sensiolabs/SensioFrameworkExtraBundle#486]
A while ago I created a PR #482 for this but since it's not being picked up yet maybe an issue is needed...

The StreamedResponse isn't actually working since it is always overwritten by a regular response anyway as can be seen here: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/EventListener/TemplateListener.php#L111

**Comment by jakzal** [comment]
Seems it was broken by #391.

**Comment by slootjes** [comment]
You're right! The test itself was wrong so it look liked it worked properly.

Just like there let's ping @fabpot to merge this PR again ;)
