### ISSUE TITLE
Why is there no 4.x tags yet ?

### ISSUE THREAD

**Issue by tristanbes** [sensiolabs/SensioFrameworkExtraBundle#487]
Hello,

The doc is by default on 4.x version where `@Entity` annotation is present (https://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/index.html) 
Yet, no tag exist, forcing us to require `-dev` version inside our `composer.json`

Is there any reasons on this ?
It's sad because 3rd party libraries have more difficulties allowing `-dev` version in their requirements.

IMO, either make 3.x doc default, or publish at least 1 stable tag on 4.x please

**Comment by fabpot** [comment]
For the docs, that's an error, should be 3.0 by default (/cc @javiereguiluz).

4.0 is not stable and not ready yet, that's why there is no tags.
