### ISSUE TITLE
Custom error message with @Security annotation

### ISSUE THREAD

**Issue by tarlepp** [sensiolabs/SensioFrameworkExtraBundle#499]
Is there a way to set custom error message with @Security annotation somehow?

Eg. if I have something like:
```
/**
 * @Route(
 *      "/{id}/roles",
 *      requirements={
 *          "id" = "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
 *      }
 *  )
 *
 * @ParamConverter(
 *     "requestUser",
 *     class="App:User"
 *  )
 *
 * @Security("is_granted('CURRENT_USER_OR_ADMIN', requestUser)")
 */
```

And if that custom voter won't grant current request I get error message like:
```
Expression \"is_granted('CURRENT_USER_OR_ADMIN', requestUser)\" denied access.
```

Imho it would be really helpfull feature if users can define their own error message on that ```@Security``` annotation.

**Comment by xabbuh** [comment]
There was a proposal in the past (see #311) which was never finished.

**Comment by scaytrase** [comment]
@xabbuh Does it make sence to reopen a proposal? I've waited a year before closing it with no reaction from maintainers.

**Comment by tarlepp** [comment]
+1 for reopen

**Comment by weaverryan** [comment]
I'd ay re-open. That PR has a lot of support it looks like. And this bundle should get a bit more attention as we prep for Symfony 4.0. Sorry the PR didn't get any attention - sometimes there's just a lot to keep track of!

**Comment by fabpot** [comment]
I'm not able to reopen myself, probably because the upstream branch does not exist anymore.

**Comment by scaytrase** [comment]
@fabpot, yes, I've deleted fork long time ago, so I'll try to repair or remade it as soon as I can

**Comment by scaytrase** [comment]
Btw, [this test line](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/Tests/EventListener/SecurityListenerTest.php#L71) looks incorrect since the signature prohibits throwing exceptions of this type, I'll propose a fix alongside, since it breaks the my new tests

**Comment by scaytrase** [comment]
Created #501 as a replacement

**Comment by fabpot** [comment]
Closing as the PR is now reopened
