### ISSUE TITLE
Remove requirement for `templating` service with `@Template`

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioFrameworkExtraBundle#500]
This is from a workshop I gave last week. We installed `twig` and also this bundle. The user tried to use `@Template`, but if tailed, because we currently require you to have the `templating` service: 

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/1ac0a9f9507cc435b116c44ce779761e393f3d55/EventListener/TemplateListener.php#L98

I can't think of any reason why we couldn't mimic the `ControllerTrait`: try `templating` first, but then fallback to using `twig` directly.

**Comment by fabpot** [comment]
Requirement has been removed on master. You should use master with Flex.
