### ISSUE TITLE
Weird bug when using constants.

### ISSUE THREAD

**Issue by Sluimers** [sensiolabs/SensioFrameworkExtraBundle#527]
The common one being:

Attempted to load class "XRepository" from namespace "AppBundle\Repository".
Did you forget a "use" statement for another namespace?

**Comment by xabbuh** [comment]
So, probably there is some code that triggers this error for you? Would you like to share that with us so that someone can actually look into it?

**Comment by Sluimers** [comment]
It's just stuff like 

class TransactieTypeController extends Controller implements ControllerConstants {

const INDEX_ROUTE_PATH = self::INDEX . TransactionType::ROUTENAME;
    const SHOW_ROUTE_PATH = self::SHOW . TransactionType::ROUTENAME;
    const NEW_ROUTE_PATH = self::NEW . TransactionType::ROUTENAME;
    const EDIT_ROUTE_PATH = self::EDIT . TransactionType::ROUTENAME;
    const DELETE_ROUTE_PATH = self::DELETE . TransactionType::ROUTENAME;
    const BULK_DELETE_ROUTE_PATH = self::BULK_DELETE . TransactionType::ROUTENAME;

    const INDEX_PAGE = self::INDEX_ROUTE_PATH . self::PAGE_EXT;
    const SHOW_PAGE = self::SHOW_ROUTE_PATH . self::PAGE_EXT;

    const INDEX_ROUTE = self::INDEX_ . TransactionType::ROUTENAME;
    const SHOW_ROUTE = self::SHOW_ . TransactionType::ROUTENAME;
    const NEW_ROUTE = self::NEW_ . TransactionType::ROUTENAME;
    const EDIT_ROUTE = self::EDIT_ . TransactionType::ROUTENAME;
    const DELETE_ROUTE = self::DELETE_ . TransactionType::ROUTENAME;
    const BULK_DELETE_ROUTE = self::DELETE_ . TransactionType::ROUTENAME;

...

/**
     * Creates a new entity.
     *
     * @param Request $request
     *
     * @Route(TransactionTypeController::NEW_ROUTE_PATH, name=TransactieTypeController::NEW_ROUTE)
     * @Method({"GET", "POST"})
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     *
     */
    public function newAction(Request $request) {
        $form = $this->createForm(TransactionTypeType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $entity = $form->getData();
            $em->persist($entity);
            $em->flush();

            return $this->redirectToRoute(self::NEW_ROUTE);
        } else if($form->isSubmitted()) {
            dump($form->getErrors(true));
            die();
        }

        return $this->render(self::NEW_PAGE, array(
            'entity_name'=>TransactionType::CLASSNAME,
            'index_route_path'=>self::INDEX_ROUTE_PATH,
            'form' => $form->createView()
        ));
    }

...
}

**Comment by Sluimers** [comment]
I tried deleting and remaking the class and it's now giving me a Segmentation fault.

**Comment by Sluimers** [comment]
Closing the issue. Turned out to be a bug on my side. The next controller class had @Route name wrong.
