### ISSUE TITLE
A question about the performance of TemplateListener

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioFrameworkExtraBundle#528]
I was profiling a Symfony 3 application and I found that TemplateListener is incredibly slow (the results are the same for 3.3.5, 3.4-beta3 and 3.4.x-dev versions):

![profile](https://user-images.githubusercontent.com/73419/32699116-afbf54bc-c7b0-11e7-9230-6fc675c86b0c.png)

But maybe I'm not understanding these numbers well:

* TemplateListener time seems to include the rendering of the Twig templates, so then the listener takes little time and Twig takes most of the time...
* ... but the chart shows that listener takes 90ms and rendering just one of the templates takes 120 ms ... so rendering time is not included?

The blue line is 90ms ... but it includes several green lines and some of them are 120ms ... something is very wrong with that chart.

So, my question: is TemplateListener very slow ... or is just a problem with that chart?

**Comment by ogizanagi** [comment]
Is `page/homepage.html.twig` rendered twice: once in the main request, once in a sub-request? It looks like there are two starting points, so it possibly messed up the chart?

**Comment by javiereguiluz** [comment]
Closing this old issue because I can no longer reproduce these strange results. Thanks!
