### ISSUE TITLE
Route annotations ignored in the Trait declaration and Controller use

### ISSUE THREAD

**Issue by alexiswbr** [sensiolabs/SensioFrameworkExtraBundle#546]
When using Trait and Route annotations, some of them are not detected/used.
Considering this implementation:

```php
<?php

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/foo", name="foo_trait_")
 */
trait FooTrait
{
    /**
     * @Route("/hello", name="hello")
     */
    public function hello()
    {
        return new Response('Hello from the trait!');
    }
}
```

```php
<?php

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class MyController extends Controller
{
    /**
     * @Route("/prefix")
     */
    use FooTrait;
}
```

The final route should be `foo_trait_hello : /prefix/foo/hello`.
But the final route is `hello : /hello`.

Neither the Route annotations used on the top of the Trait declaration and in the Controller are used.
Is it an expected behavior or a bug? That would be really useful imho.

**Comment by Tobion** [comment]
Using a prefix on a trait use is not supported yet. This would be a new feature. The routing config on this bundle has been deprecated in favor of Symfony Core. So if you want to propose this as a new feature, please open a ticket in https://github.com/symfony/symfony
