### ISSUE TITLE
Undefined method named "getParent"

### ISSUE THREAD

**Issue by alegout** [sensiolabs/SensioFrameworkExtraBundle#550]
Hello,

Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getParent" of class "src/Acme/TestBundle/AcmeTestBundle"." at /var/www/html/vendor/sensio/framework-extra-bundle/Templating/TemplateGuesser.php line 95

TemplateGuesser.php line 95:
`if (null === $parentBundleName = $bundle->getParent()) {`

Is the getParent method required? Not declared in Symfony\Component\HttpKernel\Bundle\BundleInterface.

Thank you

**Comment by xabbuh** [comment]
Which version of SensioFrameworkExtraBundle do you use? I think this should have been fixed in #506.

**Comment by alegout** [comment]
Ah yes you are right. 
I needed to go back to 3.* version cause of [issue-542](https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/542)...
