### ISSUE TITLE
Logic exception when controller returns array

### ISSUE THREAD

**Issue by tuanalumi** [sensiolabs/SensioFrameworkExtraBundle#555]
I got logic exception where returning array in controller action.

> (1/1) LogicException
> The controller must return a response (Array(aaab => dd) given).

Code in controller:

```
class DefaultController extends Controller
{
    /**
     * @Route("/default", name="default")
     * @Template()
     */
    public function index()
    {
        return ['aaab'=>'dd'];
    }
}
```

I am using Symfony 3.4.5 with `sensio/framework-extra-bundle": "5.1.5"`, using Flex structure. Template exists in `templates/default/index.html.twig`. Is there any problem with Flex structure or Symfony 3.4.5?

**Comment by jakzal** [comment]
Did you enable annotations for the view like below?

```yaml
sensio_framework_extra:
    view:        { annotations: true }
```

**Comment by tuanalumi** [comment]
Yes, I put the config in `config/packages/framework-extra.yaml`.

**Comment by Tobion** [comment]
Is this still relevant? can u provide a small example application that reproduces the problem?
