### ISSUE TITLE
Docs are confusing about @Route differences from Routing component

### ISSUE THREAD

**Issue by msheakoski** [sensiolabs/SensioFrameworkExtraBundle#568]
The [@Route and @Method](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html) section seems to duplicate a lot of information from [Routing](http://symfony.com/doc/current/routing.html), [How to Define Route Requirements](http://symfony.com/doc/current/routing/requirements.html), and [Giving {placeholders} a Default Value](http://symfony.com/doc/current/routing.html#giving-placeholders-a-default-value).

I think it would be better to reference those docs and talk more about the enhancements that FrameworkExtraBundle adds to the `@Route` annotation. Honestly, I'm not even sure myself what all of the enhancements are? `@Route("/edit/{id}") @Method({"GET", "POST"})` can simply be defined as `@Route("/edit/{id}", methods={"GET", "POST"})` (supported since v2.2.0) without FrameworkExtraBundle. `@Method` should probably just be removed from the docs and deprecated.

The only remaining enhancement that I know of is [Controller as Service](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#controller-as-service) and [automatically using @ParamConverter](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#usage) in certain situations. Am I missing any other differences?

**Comment by Tobion** [comment]
The framework bundle routing has already been deprecated. See https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/562

**Comment by msheakoski** [comment]
Ahh, that clears up many questions! I see where you updated the code, but the [docs](https://github.com/sensiolabs/SensioFrameworkExtraBundle/tree/c6ae0de128aace126a3289adea65fa0ee3b24d1d/Resources/doc) as of April still contain all of the original information about `@Route` and `@Method`. These should be removed for the 5.2 version, yes? If you wish, I can make a PR.

**Comment by Tobion** [comment]
Thanks for the reminder. I created a PR: #577

**Comment by msheakoski** [comment]
You're welcome! I will close this issue and let the PR take over from here.
