### ISSUE TITLE
Provide autowiring for PSR-7 factories

### ISSUE THREAD

**Issue by soullivaneuh** [sensiolabs/SensioFrameworkExtraBundle#575]
These factory services: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/50e8b7292425957b8fd66887504430c89bcbd83c/Resources/config/psr7.xml#L8-L9

Do not have autowiring.

Current workaround on the Kernel compilation:

```php
$aliases = ([
    // ...
    \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory::class => 'sensio_framework_extra.psr7.http_foundation_factory',
]);
foreach ($aliases as $alias => $id) {
    try {
        $container->getAlias($alias);
        throw new \RuntimeException("Alias {$alias} already exists");
    } catch (InvalidArgumentException $exception) {
        $container->setAlias($alias, $id);
    }
}
```

**Comment by florianajir** [comment]
try this configuration:
```yaml
#config/packages/sension_framework_extra.yaml
sensio_framework_extra:
    psr_message: { enabled: true }
--

**Comment by Tobion** [comment]
@soullivaneuh what do you need the autowiring for? Those classes are usually not used directly in user-land but indirectly through argument resolver/response listener.

And if the aliases are added, they should be for the interfaces (HttpMessageFactoryInterface and HttpFoundationFactoryInterface), not the implementations.
