### ISSUE TITLE
Include ParamConverter for Doctrine MongoDB ODM

### ISSUE THREAD

**Issue by alcaeus** [sensiolabs/SensioFrameworkExtraBundle#588]
In the Symfony Slack, a user was having issues getting ParamConverters to work with Doctrine MongoDB ODM. Turns out that the converter is automatically registered for ORM but not for ODM. This was previously talked about in #308, but since the issue is 2 years old I wanted to check back: would you support adding a param converter for Doctrine MongoDB ODM here or is this something that the DoctrineMongoDBBundle should register if the ParamConverter class exists?

**Comment by fabpot** [comment]
Closing as the bundle is stable and does not really evolve anymore. The next step will probably to move the most useful features directly into Symfony.
