### ISSUE TITLE
deprecated since version 5.2

### ISSUE THREAD

**Issue by heximcz** [sensiolabs/SensioFrameworkExtraBundle#595]
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/1032c7077fd1a6f24f98b5a8377938000859f35d/Routing/AnnotatedRouteControllerLoader.php#L19

Right version of deprecated since is 5.2 or 4.2 ?

**Comment by mdeboer** [comment]
The SensioFrameworkExtraBundle version numbers are not to be confused with Symfony's version numbers. They are not in sync and 5.2 is therefore correct.
