### ISSUE TITLE
SecurityUserValueResolver + Security Annotation

### ISSUE THREAD

**Issue by dron-alterpost** [sensiolabs/SensioFrameworkExtraBundle#601]
When UserInterface is used as controller argument and argument is not optional (DefaultValueResolver::supports returns false), an exception is thrown.
It is so, because ```\Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener``` is subscribed on ```\Symfony\Component\HttpKernel\KernelEvents::CONTROLLER_ARGUMENTS``` event.

For my opinion, this is bug, because controller is should not called when user is not authorized.

**Comment by jvasseur** [comment]
This is a duplicate of #574
