### ISSUE TITLE
Automatic ParamConverter Stopped working

### ISSUE THREAD

**Issue by tacman** [sensiolabs/SensioFrameworkExtraBundle#604]
The autowiring for ParamConverter stopped working recently.  I can demonstrate within my own app a working version, then a version that's broken when I do a composer update, but I'm unable to figure out which commit/version is causing the break.  I think it has to do with autowiring.

I've reproduced the bug in symfony-demo at https://github.com/survos/symfony-demo

It's the demo application with a ParamConverter that should be autowired, according to the instructions at https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter

    git clone git@github.com:survos/symfony-demo.git
    cd symfony-demo
    composer install
    bin/console server:start
   
open http://127.0.0.1:8000/es/blog/ and click on the "BUG" link that will show the error "Unable to guess how to get a Doctrine instance from the request information for parameter "post".

I realize that if I explicitly add the @ParamConverter annotation it will work, but it's all over my code and this was working perfectly until a few weeks ago.  

```php
    /**
     * @Route("/bug-posts/{postSlug}", methods={"GET"}, name="blog_post_bug")
     * When the space is removed below, this works.  But it should also work with an autowired PostParamConverter
     * @ ParamConverter("post", options={"mapping": {"postSlug": "slug"}})
     *
     *
     * NOTE: The $post controller argument is automatically injected by Symfony
     * after performing a database query looking for a Post with the 'postSlug'
     * value given in the route.
     *
     * See src/Request/ParamConverter/PostParamConverter.php
     * See https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html
     */
    public function postShowBug(Post $post): Response
```

I'm happy to share my repo and database -- although there's a lot of code, I can demonstrate it in a very isolate case.  (install the app, go to a url, it works.  composer update, go to the same url, it doesn't).

**Comment by xabbuh** [comment]
@tacman I guess this issue can be closed too now, right?

**Comment by tacman** [comment]
Or we can continue it on the symfony/symfony issue
https://github.com/symfony/symfony/issues/29819

 So yes, we can closed this.
