### ISSUE TITLE
Require component psr7 ?

### ISSUE THREAD

**Issue by Chrysweel** [sensiolabs/SensioFrameworkExtraBundle#613]
I have version symfony v3.4.* and today update my composer and update the version sensio/framework-extra-bundle and I get the following error:

```
In SensioFrameworkExtraExtension.php line 153:
                                                                          
  PSR-7 support cannot be enabled as the required dependencies are not i  
  nstalled. Try running "composer require nyholm/psr7". 
```

My question is... is mandatory this bundle ? If is mandatory.. it would to be into requirements bundle sensioFrameworkExtraBundle?

Thanks in advance.

**Comment by KittenAmelia** [comment]
Same issue here! Please fix, think your last commits may have taken it out.

**Comment by fabpot** [comment]
You should only have this message if you have explicitly enabled PSR-7 support (via `psr_message` configuration) or if you have the PSR-7 Symfony bridge. Can you confirm?

**Comment by fabpot** [comment]
A new release is out with a bug fix for that issue.

**Comment by KittenAmelia** [comment]
Confirmed okay now, Thanks Fabien!
