### ISSUE TITLE
upgrade from 5.2.4 to 5.3.1 gives `Error: Class 'Nyholm\Psr7\Factory\Psr17Factory' not found`

### ISSUE THREAD

**Issue by rbaarsma** [sensiolabs/SensioFrameworkExtraBundle#620]
I've just upgraded from sensio/framework-extra-bundle 5.2.4 to 5.3.1 in my symfony 4.2.9 project.

Now I get this message on several tests:

```
Error: Class 'Nyholm\Psr7\Factory\Psr17Factory' not found

/var/www/application/var/cache/test/ContainerGHVBRZx/getSensioFrameworkExtra_Psr7_HttpMessageFactoryService.php:9
/var/www/application/var/cache/test/ContainerGHVBRZx/srcPublicationService_KernelTestDebugContainer.php:591
/var/www/application/var/cache/test/ContainerGHVBRZx/getSecurity_Authentication_Listener_Oauth2_ApiService.php:12
/var/www/application/var/cache/test/ContainerGHVBRZx/srcPublicationService_KernelTestDebugContainer.php:591
/var/www/application/var/cache/test/ContainerGHVBRZx/getSecurity_Firewall_Map_Context_ApiService.php:13
/var/www/application/vendor/symfony/security/Http/Firewall.php:71
/var/www/application/vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:33
/var/www/application/vendor/symfony/security/Http/Firewall.php:90
/var/www/application/vendor/symfony/security-bundle/EventListener/FirewallListener.php:48
/var/www/application/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115
/var/www/application/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/var/www/application/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/var/www/application/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:145
/var/www/application/vendor/symfony/http-kernel/HttpKernel.php:126
/var/www/application/vendor/symfony/http-kernel/HttpKernel.php:67
/var/www/application/vendor/symfony/http-kernel/Kernel.php:198
/var/www/application/vendor/symfony/http-kernel/Client.php:68
/var/www/application/vendor/symfony/framework-bundle/Client.php:131
/var/www/application/vendor/symfony/browser-kit/Client.php:405
/var/www/application/tests/functional/Application/Controller/CourseApiControllerTest.php:44
```

I also get this message on other tests

```
[2019-06-04 09:09:04] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\RuntimeException: "Cannot autowire argument $serverRequest of "trikoder.oauth2.controller.token_controller:indexAction()": it references interface "Psr\Http\Message\ServerRequestInterface" but no such service exists. Did you create a class that implements this interface?" at /var/www/application/vendor/symfony/dependency-injection/Container.php line 427 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException(code: 0): Cannot autowire argument $serverRequest of \"trikoder.oauth2.controller.token_controller:indexAction()\": it references interface \"Psr\\Http\\Message\\ServerRequestInterface\" but no such service exists. Did you create a class that implements this interface? at /var/www/application/vendor/symfony/dependency-injection/Container.php:427)"} []
```
This latter problem has it's own issue too on https://github.com/trikoder/oauth2-bundle/issues/42

I'm posting a reply there too to link to this issue and tell them I"ve tried the fixes they proposed, but they are not working. Since I only updated sensio/framework-bundle, I'm not sure who needs to fix what.

Possibly related to https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/613 (I get that same error of missing requirement when I downgrade to version 5.3.0)

**Comment by JJarrie** [comment]
Look like you haven't any Psr7/17 implementation installed or configured, since 5.3.0 the bundle embeds default alias pointing to nyholm/psr7 hence your error.

**Comment by rbaarsma** [comment]
Well I haven't read anywhere that this minor version (5.2 to 5.3) has a breaking change where I need to do anything manually to keep my code working. If it's a new requirement, it should simply be in the composer.json of sensio/framework-extra-bundle, right? Should be easy to update your application without having to go over the internet to find out what this specific errors means.. and without the information whether or not I'm meant to simply install this extra library that is not in any of the requirements..?

**Comment by rbaarsma** [comment]
For good measure I tried `composer update sensio/framework-extra-bundle --with-dependenciesc`, but that doesn't fix the problem either

**Comment by X-Coder264** [comment]
@rbaarsma As documented in https://github.com/trikoder/oauth2-bundle/pull/43 , you should explicitly require a PSR-7 implementation in your project, that was a breaking change which was caused by https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/608

**Comment by JJarrie** [comment]
This is documented [here](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html) and [here](https://symfony.com/doc/current/components/psr7.html), nyholm/psr7 is not a dependency of bundle, this change allows to using psr specifications in way to decoupling the http implementation. There is no breaking change for your code.

**Comment by rbaarsma** [comment]
Well it's breaking if my code breaks without the `nyholm/psr7` installed, right?

From the symfony documentation https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html it is very clear the `nyholm/psr7` bundle is a *feature* that can be enabled.

I don't want to be an annoyance here - I could perhaps even install the psr7 thingy and be done with it - I just want to help the community and others, who want to simply update their Symfony application and run into problems where optional bundles that are not installed are giving fatal errors. 

I haven't tested if you get the same error without the trikoder/oauth2-bundle and I'm not sure whether the problem is there or in the this bundle, but either way it's annoying when you cannot update your application without breaking stuff.. just looking to help.

**Comment by X-Coder264** [comment]
@JJarrie #608 was a breaking change for the users of our bundle as the `sensio_framework_extra.psr7.http_message_factory` service ID no longer pointed to the `Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory` (the bundle depended on the Diactoros PSR-7 implementation) and just by updating `SensioFrameworkExtraBundle` to 5.3.0 everything broke.

@rbaarsma Just require `nyholm/psr7`. Or if you want to keep using the Diactoros implementation check the documentation about doing that which is written as well in https://github.com/trikoder/oauth2-bundle/pull/43

**Comment by fabpot** [comment]
So, nothing to change right? I must admit that I know nothing about all the PSR-7 dance we're doing here. To be honest, I would be the first to be very happy to remove everything related to PSR-7 from the bundle.

**Comment by rbaarsma** [comment]
> @rbaarsma Just require `nyholm/psr7`. Or if you want to use the Diactoros implementation check the documentation about doing that which is written as well in [trikoder/oauth2-bundle#43](https://github.com/trikoder/oauth2-bundle/pull/43)

Unfortunately installing nyholm/psr7 alone doesn't fix the problem, because a new error is thrown:
```
Error: Class 'Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory' not found

/var/www/application/var/cache/test/ContainerWcxQs4n/getSensioFrameworkExtra_Psr7_HttpMessageFactoryService.php:19
/var/www/application/var/cache/test/ContainerWcxQs4n/srcPublicationService_KernelTestDebugContainer.php:591
/var/www/application/var/cache/test/ContainerWcxQs4n/getSecurity_Authentication_Listener_Oauth2_ApiService.php:12
/var/www/application/var/cache/test/ContainerWcxQs4n/srcPublicationService_KernelTestDebugContainer.php:591
/var/www/application/var/cache/test/ContainerWcxQs4n/getSecurity_Firewall_Map_Context_ApiService.php:13
/var/www/application/vendor/symfony/security/Http/Firewall.php:71
/var/www/application/vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:33
/var/www/application/vendor/symfony/security/Http/Firewall.php:90
/var/www/application/vendor/symfony/security-bundle/EventListener/FirewallListener.php:48
/var/www/application/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115
/var/www/application/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/var/www/application/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/var/www/application/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:145
/var/www/application/vendor/symfony/http-kernel/HttpKernel.php:126
/var/www/application/vendor/symfony/http-kernel/HttpKernel.php:67
/var/www/application/vendor/symfony/http-kernel/Kernel.php:198
/var/www/application/vendor/symfony/http-kernel/Client.php:68
/var/www/application/vendor/symfony/framework-bundle/Client.php:131
/var/www/application/vendor/symfony/browser-kit/Client.php:405
/var/www/application/tests/functional/Application/Controller/SubscriptionApiControllerTest.php:19
```

 I think I need to install psr-http-message-bridge too, but when I run `docker-compose exec php composer require nyholm/psr7 symfony/psr-http-message-bridge`, it refuses..

```
  Problem 1
    - trikoder/oauth2-bundle v1.1.0 requires symfony/psr-http-message-bridge 1.0.* -> satisfiable by symfony/psr-http-message-bridge[v1.0.0, v1.0.1, v1.0.2] but these conflict with your requirements or minimum-stability.
    - trikoder/oauth2-bundle v1.1.0 requires symfony/psr-http-message-bridge 1.0.* -> satisfiable by symfony/psr-http-message-bridge[v1.0.0, v1.0.1, v1.0.2] but these conflict with your requirements or minimum-stability.
    - trikoder/oauth2-bundle v1.1.0 requires symfony/psr-http-message-bridge 1.0.* -> satisfiable by symfony/psr-http-message-bridge[v1.0.0, v1.0.1, v1.0.2] but these conflict with your requirements or minimum-stability.
    - Installation request for trikoder/oauth2-bundle ^1.1 -> satisfiable by trikoder/oauth2-bundle[v1.1.0].
```

Personally I can never figure out why composer isn't able to solve these problems..  usually there is no real conflict.. but that's another story for another issue ;) 

For now I've just downgraded sensio/framework-extra-bundle to 5.2.4 and will hope this issue is resolved at some point..

**Comment by rbaarsma** [comment]
Oh I'm probably wrong I need psr-http-message-bridge, because I just noticed it is already installed

```
bash$ composer show | grep message
php-http/message                    1.7.2   HTTP Message related tools
php-http/message-factory            v1.0.2  Factory interfaces for PSR-7 HT...
psr/http-message                    1.0.1   Common interface for HTTP messages
symfony/psr-http-message-bridge     v1.0.2  PSR HTTP message bridge
```

**Comment by rbaarsma** [comment]
also not sure why guzzle isn't used automatically. It's psr7 too, right?

**Comment by X-Coder264** [comment]
@rbaarsma You need `dev-master` for `trikoder/oauth2-bundle` because a version with the fix for  `SensioFrameworkExtraBundle 5.3.0` hasn't been tagged yet. The oauth2-bundle bundle also requires `symfony/psr-http-message-bridge` `^1.2` so there is no need to manually require it in your app.

Anyhow, this issue should be closed as there is nothing left to be done here @fabpot.

@rbaarsma Please let's move the discussion back into https://github.com/trikoder/oauth2-bundle/issues/42

**Comment by rbaarsma** [comment]
Yeah I guess it's a `trikoder/oauth2-bundle` bug. I'll move the discussion there. Closing.

**Comment by Ocramius** [comment]
Just dropping in here as a follow-up for people that may be lost: overall, the fact that a specific PSR-7 implementation that is **not** included in `composer.json` `"require"` is referenced in config is the problem here. It's gone in `master`, which is OK.

The solution I found to be working well enough to be able to use a modern HTTP abstraction without adding more and more alternate PSR-7 implementations is to use something like https://github.com/php-http/discovery and wiring its services:

```yml
services:

    Psr\Http\Message\ServerRequestFactoryInterface:
        factory: [Http\Discovery\Psr17FactoryDiscovery, findServerRequestFactory]
    Psr\Http\Message\StreamFactoryInterface:
        factory: [Http\Discovery\Psr17FactoryDiscovery, findStreamFactory]
    Psr\Http\Message\UploadedFileFactoryInterface:
        factory: [Http\Discovery\Psr17FactoryDiscovery, findUploadedFileFactory]
    Psr\Http\Message\ResponseFactoryInterface:
        factory: [Http\Discovery\Psr17FactoryDiscovery, findResponseFactory]
```

Be aware that you need an http factory **implementation** for this to work:

```sh
composer require psr/http-factory-implementation
```

Shout out to @php-http for their awesome discovery tool :-)
