### ISSUE TITLE
has_role is broken in Symfony 3.4 in 5.4.0

### ISSUE THREAD

**Issue by ostrolucky** [sensiolabs/SensioFrameworkExtraBundle#628]
Because of this change https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/e5f9bbf26fabcc1e30ef75c76e6de689a063c5d9#diff-9bba23159f3d837b5f7261925414651fL101

This line https://github.com/symfony/symfony/blob/d9833ace32c69681a0a01f309f5f2b6cc57b0485/src/Symfony/Component/Security/Core/Authorization/ExpressionLanguageProvider.php#L54 now receives array of objects instead of array of strings and fails. 

We have hundreds of tests failing with HTTP 403 error

**Comment by xabbuh** [comment]
Are you sure? Because of the changes made on line 90 and line 92 `$roles` should be an array of strings there.

**Comment by esbobkov** [comment]
Same problem

**Comment by xabbuh** [comment]
Can you please try to debug why `$roles` is not an array of strings at this stage?

**Comment by ostrolucky** [comment]
neither `\Symfony\Component\Security\Core\Role\RoleHierarchyInterface::getReachableRoles` nor `\Symfony\Component\Security\Core\Authentication\Token\TokenInterface::getRoles` return array of strings

**Comment by ostrolucky** [comment]
I will create a PR

**Comment by xabbuh** [comment]
@ostrolucky good catch, the `array_map()` part that was previously present needs to be added to the newly added `else` branch
