### ISSUE TITLE
[FrameworkExtraBundle] @Method annotation is deprecated error

### ISSUE THREAD

**Issue by Arman-Hosseini** [sensiolabs/SensioFrameworkExtraBundle#632]
Symfony Profiler told me: 
**User Deprecated: The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Method" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.** 

And I went to **'Symfony\Component\Routing\Annotation\Route'** but didn't find the **@Method()** to use.
Did something go wrong?

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/d30e4ab03bc56654ec8b52aef9a904d99cfd50a6/Configuration/Method.php#L14-L23

**Comment by jvasseur** [comment]
The message is a bit misleading here, what you need to do is use the `methods` attribute of the `Route` annotation (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Routing/Annotation/Route.php#L31).

**Comment by Arman-Hosseini** [comment]
Exactly what I mean is that the message is a little confusing.
The following should be used:
`use Symfony\Component\Routing\Annotation\Route as Method;`
