### ISSUE TITLE
ODM Repository return null instead of false

### ISSUE THREAD

**Issue by jjouanno** [sensiolabs/SensioFrameworkExtraBundle#636]
Hi,

DoctrineParamConverter try to get value by id before to try by field.
The find method return Repository value at end: 
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/197eb89b488085fb638fb5107bc49dd74b1c364c/Request/ParamConverter/DoctrineParamConverter.php#L142

But ODM Repository return null instead of waiting false:

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/197eb89b488085fb638fb5107bc49dd74b1c364c/Request/ParamConverter/DoctrineParamConverter.php#L91

So I can convert only by id field.

**Comment by fabpot** [comment]
Closing as I'm not using the ODM. I suppose that the ODM and the ORM should return the same thing.
