### ISSUE TITLE
SF 4.4/5.0 deprecates/removes IsGranted multi-attribute usage.

### ISSUE THREAD

**Issue by mattjanssen** [sensiolabs/SensioFrameworkExtraBundle#645]
https://github.com/symfony/symfony/pull/33584 removes the ability to pass an array of attributes to `isGranted()` and `decide()` methods. Should the `@IsGranted()` annotation be updated to not allow arrays, too?

If so, let's not forget to revert this documentation commit (https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/97cc360add63a1376bbbe8e1b912c43c07640ef2) I made in July.

**Comment by wouterj** [comment]
I think it's best to deprecate passing multiple attributes for `@IsGranted` as well, for consistency sake. If we agree, I'm happy to make a PR with the changes

**Comment by fabpot** [comment]
I agree.

**Comment by wouterj** [comment]
Alright, see #648 :)

**Comment by carlospauluk** [comment]
Ok, so now @IsGranted({"ROLE_ADMIN"}, statusCode=403) doesn't work anymore. We need to use @IsGranted("ROLE_ADMIN", statusCode=403).
