### ISSUE TITLE
Missing doctrine/persistence 

### ISSUE THREAD

**Issue by mazarini** [sensiolabs/SensioFrameworkExtraBundle#646]
Hi,

They is no more doctrine/persistence with dev-master but still use it in TemplateGuesser and ControllerListener.

**Comment by andrew-demb** [comment]
Hello.
I think you should manually require this dependency.

2maintainers: can we add `doctrine/persistence` to suggest section?

**Comment by fabpot** [comment]
We've remove it as it is an optional dependency. If you need it, it means that you are using Doctrine ORM which includes doctrine/persistence as a transitive dep.

**Comment by mazarini** [comment]
I just play with twig and wenpack. I use no database.
The doctrine package I use  : 
```
+------------------------------------+-------------------------------+-------------+
| why ?                              | because                       | composer    |
+------------------------------------+-------------------------------+-------------+
| doctrine/annotations               | sensio/framework-extra-bundle | require     |
| doctrine/inflector                 | symfony/maker-bundle          | require-dev |
| doctrine/lexer                     | sensio/framework-extra-bundle | require     |
```
I'm not sure to understand where my problem come from. I have no ref to doctrine/persistence in my config.
What I understand : if I use doctrine/persistence, SensioFrameworkExtraBundle need doctrine/persistence to find real class / proxy class in some case. But I'm not good enought with symfony.
