### ISSUE TITLE
FOSRest - Bug after an update

### ISSUE THREAD

**Issue by ClementVincent** [sensiolabs/SensioFrameworkExtraBundle#649]
Hi, 

I'm using FOSRest and since the new update of SensionFrameworkExtraBundle (5.5) I'm facing this error :
“Undefined offset: 0” in vendor\friendsofsymfony\rest-bundle\EventListener\ViewResponseListener.php line 99

```
namespace FOS\RestBundle\EventListener;
/**
 * The ViewResponseListener class handles the View core event as well as the "@extra:Template" annotation.
 *
 * @author Lukas Kahwe Smith <smith@pooteeweet.org>
 *
 * @internal
 */
class ViewResponseListener implements EventSubscriberInterface
{
   ......

    /**
     * Renders the parameters and template and initializes a new response object with the
     * rendered content.
     *
     * @param GetResponseForControllerResultEvent $event
     */
    public function onKernelView(GetResponseForControllerResultEvent $event)
    {
        ......
        $configuration = $request->attributes->get('_template');
        ......
        if ($configuration instanceof ViewAnnotation) {
            ......
            list($controller, $action) = $configuration->getOwner();   <-------------- At this line
            $vars = $this->getDefaultVars($configuration, $controller, $action);
            ......
         }
     }
}
```
This come from this change : 
```
namespace Sensio\Bundle\FrameworkExtraBundle\Configuration;
/**
* The Template class handles the Template annotation parts.
*
* @author Fabien Potencier <fabien@symfony.com>
* @Annotation
 */
class Template extends ConfigurationAnnotation
{

         ....

        ----------------- After --------------------

        /**
         * The controller (+action) this annotation is set to.
         *
         * @var array
         */
        private $owner = [];

       ----------------- Before --------------------
        /**
         * The controller (+action) this annotation is set to.
         *
         * @var array
         */
        private $owner;
```

Do you guys have any clue ?

Origin : https://stackoverflow.com/questions/58528837/fosrestbundle-undefined-offset-0-in-vendor-friendsofsymfony-rest-bundle-eve

**Comment by HeahDude** [comment]
This should have been fixed by #643.

**Comment by ClementVincent** [comment]
Hello @HeahDude,

I think this fix is the source of the bug.
With an empty list, this piece of code isn't working while it was possible with a null:
`list($controller, $action) = $configuration->getOwner(); `

**Comment by Tobion** [comment]
what @ClementVincent say seems to be true: https://3v4l.org/O5N53

**Comment by ClementVincent** [comment]
Is there any news ? Do you think that the FosRestBundle team should be informed ?

As a temporary workaround, those who face this problem can downgrade SensionFrameworkExtraBundle to 5.4

**Comment by fabpot** [comment]
I think FosRestBundle should be fixed.

**Comment by xabbuh** [comment]
Can you confirm that FriendsOfSymfony/FOSRestBundle#2097 fixes the issue?

**Comment by ClementVincent** [comment]
I'm not really familiar with the Sensio\Bundle\FrameworkExtraBundle\Configuration\Template class so I don't know which values the $owner attribute can take.
But if I'm right, if the owner list is only 1 element long the code will raise an error even with your patch.
What about this test instead ?
```php
$owner = $configuration->getOwner();
if (count($owner) != 2) {
   $owner = null;
}
[$controller, $action] = $owner;
```

Anyway, the patch will be dirty and weak I guess because the list is too permissive. 
The assertion count($owner) == 2 is not ensured by the language itself like with Tuple in other languages so the number of element in $owner can be bigger or lower than 2.
Same thing, we cannot be sure that $controller is at index 0 and $action at index 1.
