### ISSUE TITLE
Opcache preloading requires expression-language component

### ISSUE THREAD

**Issue by leongersen** [sensiolabs/SensioFrameworkExtraBundle#668]
I'm having trouble getting the php7.4 opcache preloading in Symfony 4.4 to work. It seems like the service definition for `\Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage` is not properly removed, and autoloading it triggers the loading of `\Symfony\Component\Security\Core\Authorization\ExpressionLanguage`, which throws a `LogicException`.

I'm using:
```
symfony/* @ 4.4
sensio/framework-extra-bundle @ v5.5.3
```

```
PHP Fatal error:  Uncaught LogicException: The "Symfony\Component\Security\Core\Authorization\ExpressionLanguage" class requires the "ExpressionLanguage" component. Try running "composer require symfony/expression-language". in .../symfony/vendor/symfony/security-core/Authorization/ExpressionLanguage.php:18
Stack trace:
#0 .../symfony/vendor/composer/ClassLoader.php(445): include()
#1 .../symfony/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 .../symfony/vendor/sensio/framework-extra-bundle/src/Security/ExpressionLanguage.php(21): spl_autoload_call()
#4 .../symfony/vendor/composer/ClassLoader.php(445): include('...')
#5 .../symfony/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#6 [internal function]: Co in .../symfony/vendor/symfony/security-core/Authorization/ExpressionLanguage.php on line 18
```

Preloading works as expected when installing `expression-language`. Could this be an issue in Symfony itself, or in this bundle?

**Comment by fabpot** [comment]
Pre-loading did not work well on early versions of PHP 7.4. We also fixed quite a few bugs in support in Symfony. I'm closing as adding the dependency is just a workaround.
