### ISSUE TITLE
[Docs][Security] Documentation improvement?

### ISSUE THREAD

**Issue by DonCallisto** [sensiolabs/SensioFrameworkExtraBundle#678]
Looking at https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html#security I think we're missing two possibile scenarios:

1. What happen when I annotate the whole controller?
2. What happen when I annotate both the whole controller and a specific action?

WDYT? The enhancement is worthy?

**Comment by DonCallisto** [comment]
Did anyone had a chance to look at this?

**Comment by naitsirch** [comment]
It seems like your first point is already fixed. In the current version it is said:

> You can also add @IsGranted or @Security annotations on a controller class to prevent access to all actions in the class.
