### ISSUE TITLE
@IsGranted does not work for arrays

### ISSUE THREAD

**Issue by yaotzin1** [sensiolabs/SensioFrameworkExtraBundle#683]
Hi,

I tried to write a controller, which was guarded by IsGranted annotation. I was surprised when I found a problem with an annotation like @IsGranted({"ROLE_ADMIN"}) which does not work. But for example, @IsGranted("ROLES_ADMIN) works as expected... I checked another project, where I use it in a similar way for a greater number of roles (I did not spotted any problem in this project). 

`    /**
     * @Route(methods={"POST"})
     * @IsGranted({RolesEnum::ROLE_ADMIN}, statusCode=403)
     * @param  Request  $request
     */
    public function createUser(Request $request, UserPasswordEncoderInterface $encoder): Response
    {`

It seems that annotation stops working for array of allowed roles. 

Env: Symfony 5.0.8, 
"sensio/framework-extra-bundle": "^5.5",

In previous project (this one where it works):
Symfony 4.4.7
"sensio/framework-extra-bundle": "^5.3",

Thanks in advance

**Comment by xabbuh** [comment]
That's probably because the Symfony Security component dropped support for passing multiple attributes to voters.

**Comment by xabbuh** [comment]
see symfony/symfony#33584

**Comment by yaotzin1** [comment]
> That's probably because the Symfony Security component dropped support for passing multiple attributes to voters.

So then what is the proper approach then, what if I want to allow functionality for multiple roles? I should use multiple IsGranted annotations? Or maybe use Security?

**Comment by xabbuh** [comment]
You can use the `@Security` annotation with an expression that does this (similarly to what is described here: https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html#security).

**Comment by yaotzin1** [comment]
Ok then, as we have new approach for that, we can close this issue
