### ISSUE TITLE
Backport test namespace fixes to v5.4

### ISSUE THREAD

**Issue by xelan** [sensiolabs/SensioFrameworkExtraBundle#694]
**Bundle version(s) affected**: 5.4.x

**Description**  
Recent composer versions show autoloader warnings for various classes, e.g.
```
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\DependencyInjection\AddParamConverterPassTest located in ./vendor/sensio/framework-extra-bundle/Tests/DependencyInjection/Compiler/AddParamConverterPassTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**How to reproduce**  
Install a Symfony 3.4 (LTS) project which uses the SensioFrameworkExtraBundle in version 5.4 with deprecation notices enabled.
To trigger the notice, composer autoloader optimization must be enabled.

**Possible Solution**  
Backport https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/677 to 5.4 

**Additional context**  
As the current version of SensioFrameworkExtraBundle 5.5 does not support the maintained Symfony version 3.4 anymore, we propose to backport the fixes to avoid autoloader warnings with recent composer versions.

Thank you very much, best regards from Austria

**Comment by fabpot** [comment]
Closing as 3.4 is not maintained anymore.
