### ISSUE TITLE
@IsGranted annotation throws a missing subject exception when subject is null

### ISSUE THREAD

**Issue by nfragnet** [sensiolabs/SensioFrameworkExtraBundle#699]
Hello,

Here is my use case:

This does not work.

```php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
​
/**
 * @IsGranted("folder_show", subject="folder")
 */
public function showAction(Folder $folder = null)
{
    // IsGrantedListener throws an exception when folder is null
}
```

However, this workaround does the trick:

```php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
​
/**
 * @Security("is_granted('folder_show', folder)")
 */
public function showAction(Folder $folder = null)
{
    // Everything is ok and my voter is reached whether $folder is an instance of Folder or null
}
```

From what I understood the IsGrantedListener prevents the subject to be null whereas it's a valid value for the `AuthorizationCheckerInterface::isGranted` method.

```php
namespace Sensio\Bundle\FrameworkExtraBundle\EventListener;

class IsGrantedListener implements EventSubscriberInterface
{
    //...
    public function onKernelControllerArguments(KernelEvent $event)
    {
        // This is the part where something went wrong
        if (!isset($arguments[$subjectRef])) {
            throw $this->createMissingSubjectException($subjectRef);
        }
        
        //... I would suggest to replace by
        if (!array_key_exists($subjectRef, $arguments)) {
            throw $this->createMissingSubjectException($subjectRef);
        }

        $subject = $arguments[$subjectRef];

        // ...

        if (!$this->authChecker->isGranted($configuration->getAttributes(), $subject))
        { 
            // ... 
        }
    }
```

There is two places where `isset` is used to check if there is an argument with that name.
One if the subject is an array, and the other if the subject is a string.

Please tell me if it seems relevant to you and I'll open a PR, or if I missed something 😅

**Comment by Pixelshaped** [comment]
I think you raise a valid point. Those two annotations should probably do the exact same thing.

**Comment by Raistlfiren** [comment]
Just to follow up on this. I also noticed the issue with strings. For example, I had the annotation 
`@IsGranted("view", subject="App\Entity\Example")` and it kept on failing with the same error.

> "Could not find the subject "App\Entity\Example" for the @IsGranted annotation. Try adding a "$App\Entity\Example" argument to your controller method."


Using the `@Security` annotation or completely overwriting the isGrantedListener fixed the problem too. If anyone else Googles this issue or runs into this problem, then I hope this helps.

**Comment by stof** [comment]
@Raistlfiren the `subject` property of the `@IsGranted` annotation is referring to an argument of the controller. If you need something else, using `@Security` is the way to go.

@nfragnet can you open a PR using your suggested fix ? Using `array_key_exists` is indeed the solution.
