### ISSUE TITLE
Backporting Doctrine BC Break fixes within v5.5.x for compatibility with PHP 7.1

### ISSUE THREAD

**Issue by Harry-Dunne** [sensiolabs/SensioFrameworkExtraBundle#700]
Hi,

Version 5.6.0 contains BC break fixes for Doctrine. Could these fixes be backported to version 5.5, the last release compatible with PHP 7.1 ?

Right now, it's impossible to create a new Symfony project >=4.4.13 working out of the box with PHP 7.1, as I describe in this issue : https://github.com/symfony/symfony/issues/38057

Regards,

Eric

**Comment by fabpot** [comment]
I've just released v5.5.7 which should fix this issue.

**Comment by Harry-Dunne** [comment]
Thanks Fabien!
