### ISSUE TITLE
I am working on upgrade SF 2.6 to SF 4.4

### ISSUE THREAD

**Issue by zhasan0** [sensiolabs/SensioFrameworkExtraBundle#704]
I face this problem in symfony 4.4.
"The "sensio_framework_extra.view.guesser" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."

![Capt1ure](https://user-images.githubusercontent.com/42202246/100151316-33f70e80-2ecb-11eb-8d8f-73750119497c.PNG)
![Capture](https://user-images.githubusercontent.com/42202246/100151322-348fa500-2ecb-11eb-8ede-1264293e4a87.PNG)

What can I do.

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions, please use any StackOverflow.

Thanks!
