### ISSUE TITLE
Symfony 5.2 and native PHP8 annotations.

### ISSUE THREAD

**Issue by pkly** [sensiolabs/SensioFrameworkExtraBundle#706]
Seems like the bundle should work with symfony 5.2, but as far as I can see there's no support for php8 annotations included. 
It'd be lovely if this feature could be added, as the main annotations in symfony 5.2 are already available as PHP8 annotations.

**Comment by Yoann-TYT** [comment]
Hi @pkly !
I propose a pull request about that https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/707 
Feel free to review it and comment it :) 

Thanks !
