### ISSUE TITLE
Psr7 is used implicitly and breaks configuration

### ISSUE THREAD

**Issue by Wirone** [sensiolabs/SensioFrameworkExtraBundle#709]
I wanted to add my 2 cents to #620 because I got the same error after today's update, but I decided to raise new issue.

I use `ekreative/uuid-extra-bundle` which requires `sensio/framework-extra-bundle` which [defines aliases](src/Resources/config/psr7.xml) based on `nyholm/psr7` without requiring that package explicitly (it's in `require-dev`). Today I've updated `sentry/sentry-symfony` to 4.0 (PHP8 support) and in the end I got:

> Uncaught Error: Class "Nyholm\Psr7\Factory\Psr17Factory" not found

I was able to get rid of this error by disabling `psr_message` in `config/packages/sensio_framework_extra.yaml` BUT I took a look at `Sensio\Bundle\FrameworkExtraBundle\DependencyInjection\Configuration` and it seems like PSR7 feature is enabled if `HttpFoundationFactoryInterface` from `symfony/psr-http-message-bridge` exists. In my case this package is required by Sentry package, so basically my application broke down because of implicit requirement for `sensio/framework-extra-bundle` AND `symfony/psr-http-message-bridge`, each required by different packages. Seems like checking for `HttpFoundationFactoryInterface` only is too optimistic and it not guarantee this feature will work.

I think this bundle should do one of those:
- `psr7.xml` should be loaded by default only if all classes used there exist (probably checking for `Nyholm\Psr7\Factory\Psr17Factory` would do the trick)
- explicitly require `nyholm/psr7`, which will solve all required dependencies

Let me know if this will be considered as bug so maybe I can work on it.

**Comment by fabpot** [comment]
See my "fix" in #710

**Comment by Wirone** [comment]
@fabpot yeah, if you want to fix this issue in *that way*, it will work too - it's up to you :wink: I don't know this feature/bundle well enough to help on decision-making level, I just wanted to point that default configuration needs a tweak. Anyway, thanks for very quick reaction :+1:

**Comment by fabpot** [comment]
Fixed in upcoming 6.0

**Comment by jeroennoten** [comment]
Is there a plan/schedule for when 6.0 will be released?

**Comment by fabpot** [comment]
6.0 just released.

**Comment by jeroennoten** [comment]
Awesome! Thanks @fabpot
