### ISSUE TITLE
Are these tags supposed to mirror Symfony's?

### ISSUE THREAD

**Issue by Bilge** [sensiolabs/SensioFrameworkExtraBundle#715]
If I use Symfony 5.1 should I remain on `sensio/framework-extra-bundle: ^5` because the version compatibility is mirrored, or do the versions not match at all and thus it is recommended to upgrade this library alone to v6 now? If that is the case, should I use `sensio/framework-extra-bundle: *` as my dependency constraint?

**Comment by nicolas-grekas** [comment]
This repo has its own versioning scheme.
