### ISSUE TITLE
Docs are missing support for attribute syntax

### ISSUE THREAD

**Issue by fridde** [sensiolabs/SensioFrameworkExtraBundle#718]
As I am currently trying to migrate my codebase from PHP 7.4 to 8.0 while simultaneously migrating Symfony 5.0 to 5.2, I am sometimes struggling with the syntax for attributes (which I prefer over annotations). While it can seem trivial to implement the change, it's still nice to see the expected result.

I was trying to find examples I could analyze, but saw that none of the [official docs for SensioFrameworkExtraBundle](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html) acknowledge that attributes even work (even though the code obviously is adapted).

Is that by choice? Or is the project still waiting for more widespread adoption of the attribute syntax? Or is it just that nobody has had the time to do that?

**Comment by stof** [comment]
Well, the PR adding support for attributes was not updating the doc to show them. And nobody did it after that. So I don't think that's an explicit choice.
Contributions to the doc are welcome. the source is in `src/Resources/doc/`

Note however that the documentation should not remove annotations entirely in favor of attributes, as this bundle still supports PHP 7.

**Comment by denisvmedia** [comment]
I added the relevant docs with #731.

**Comment by denisvmedia** [comment]
Accorxing to @derrabus 's suggestions I added code blocks, so it's not anymore annotation oriented, it gives two separate examples.

**Comment by denisvmedia** [comment]
@fabpot I noticed that [the official docs](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html) are actually still for the version 5.0 only. However, we already have 6.1 released. Is it intentional or something that is yet to be fixed?

**Comment by fabpot** [comment]
@denisvmedia Fixed now.

I've also fixed some markup issues here: https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/5e7f568160ecae3c16b14264bbc57d2a4a854df9

**Comment by denisvmedia** [comment]
Thank you!
