### ISSUE TITLE
Attempted to call an undefined method named "isBuiltin" of class "ReflectionUnionType".

### ISSUE THREAD

**Issue by erkens** [sensiolabs/SensioFrameworkExtraBundle#724]
I'm using PHP 8.0.3 (from the docker image php:8.0.3-fpm-alpine) with Symfony 5.2.6 and version 6.1.2 of sensio/framework-extra-bundle.

I have created a simplified action that somehow reflect my issue (in legacy code) and it is also reproducable with it.
```php
    #[Route('/test', name: 'testAction', defaults: ['stuff' => false])]
    public function testAction(int|false $stuff): Response
    {
        // do stuff
        return new Response();
    }
```

And when calling this action I got the exception: 'Attempted to call an undefined method named "isBuiltin" of class "ReflectionUnionType".'

```php
// in vendor/sensio/framework-extra-bundle/src/EventListener/ParamConverterListener.php (line 75-82)
    private function autoConfigure(\ReflectionFunctionAbstract $r, Request $request, $configurations)
    {
        foreach ($r->getParameters() as $param) {
            $type = $param->getType();
            $class = null !== $type && !$type->isBuiltin() ? $type->getName() : null;
            if (null !== $class && $request instanceof $class) {
                continue;
            }
// ...
```

Here on line 79 `$type` is of ReflectionUnionType and with PHP 8, that doesn't have the `isBuiltin()`-method anymore according to the documentation: https://www.php.net/manual/en/class.reflectiontype.php

For me the fix would be "easy", just don't use union-types (and in my case it could be changed to ?int instead of int|false) or put them back in the php-doc where I had it before.  Personally I don't like union-types, but sometimes with legacy code you can't get rid of it that easy, that is why I create this bug-report. 

Maybe when I got some time I will try to create a PR for this, but again, for me this is not a big issue.

**Comment by nicolas-grekas** [comment]
Thanks for the report. Can you please send a PR to fix that?

**Comment by erkens** [comment]
> Thanks for the report. Can you please send a PR to fix that?

When I'm able and have some time I will, but I'm not that familiar with this code, so I need to setup an envirnoment for testing this (on several PHP versions), and find a good solution... So when someone else have a PR, please do.

**Comment by jgrygierek** [comment]
Still nothing?

**Comment by erkens** [comment]
oops, totally forgot this one... sorry, I'm not using union types (because I find them stupid) so it isn't an issue for me. Also I don't know if it is maybe fixed already in some way last year?

So I close this issue, but please feel free to reopen it...
