### ISSUE TITLE
BC break in 6.1.0

### ISSUE THREAD

**Issue by kevinpapst** [sensiolabs/SensioFrameworkExtraBundle#733]
Hello!

When upgrading a project to the latest release, I ran into a BC break which is a blocker right now for me.

It was introduced by @Yoann-TYT in #707 when adding the PHP8 Attributes support. 

Reason is this line:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/5e7f568160ecae3c16b14264bbc57d2a4a854df9/src/Configuration/Security.php#L62

which overwrites the default `protected $message = 'Access denied.';` with `string $message = null` from the constructor.
This triggers a "strange" exception message. Instead of seeing `Access denied` I now see `Expression "is_granted('my_acl')" denied access.` caused by the SecurityListener:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/5e7f568160ecae3c16b14264bbc57d2a4a854df9/src/EventListener/SecurityListener.php#L79

because the $message is now null instead of `Access denied.` in the $configuration object.

I guess the same exception message is triggered when using Attributes. In both cases the default message `Access denied` should be used. Right now, I am using the Exception message in an API response and I definitely don't want to leak the Security expression which raised the Exception.

**Comment by sstok** [comment]
FYI. This is a major version increase, so BC breakage is expected and accepted.

**Comment by kevinpapst** [comment]
@sstok Mr obvious 😁 thanks for your two minutes, but your answer doesn't add anything helpful to the the discussion.

First of all, the problem happened in #707, which was merged into 6.1 (as the title says) and this is not a major version.

But more importantly:
- this is not an intended change but obviously a mistake
- this change now leaks internal information on EVERY `VoterInterface::ACCESS_DENIED` when the `is_granted('XYZ')` expression does not specify an explicit message

I haven't seen many projects that specify this message, even the documentation mentions it only very late and most examples  never include it. I would even argue that the fallback message itself is a problem and should be changed, but that is up for another discussion.

Maybe I am not good explaining why I think this BC break is rather critical:

On probably the most important entry point into the Voter world (regarding permission checks in Symfony projects) the exception message changed, now **leaking internal project information**.

A message like:
```
Expression "is_granted('my_acl')" denied access.
```
is never ever something you want to see in any application response.

**Comment by fabpot** [comment]
@kevinpapst  Can you submit a PR to fix this issue?

**Comment by kevinpapst** [comment]
I'll give it a try

**Comment by sstok** [comment]
Sorry I missed x.1 part 😅

**Comment by kevinpapst** [comment]
PR available in #734
