### ISSUE TITLE
Add param converter for symfony/uid

### ISSUE THREAD

**Issue by RikudouSage** [sensiolabs/SensioFrameworkExtraBundle#765]
As the title says, it would be nice to add param converters for classes from symfony/uid so that users can typehint Uuid and Ulid classes in their controllers.

I'm willing to implement it myself if @fabpot agrees that it should be added to this bundle.

**Comment by nicolas-grekas** [comment]
This has already been implemented in https://github.com/symfony/symfony/pull/44665
