### ISSUE TITLE
Bug when convert datetime param on symfony 6.1

### ISSUE THREAD

**Issue by Quovandius** [sensiolabs/SensioFrameworkExtraBundle#770]
Hello here,

I have migrate one of my project on Symfony 6.1 version, and I have a bug on one controller function :
```
  /**
     * @Route("/print-{p_dateStart}_{p_dateEnd}", name="print_stat", methods={"GET"})
     */
    public function printAction(\Datetime $p_dateStart, \Datetime $p_dateEnd): Response
    {
        dump($p_dateStart);
        dump($p_dateEnd);
    }
```

On Symfony 6.0 version, my param has been converted into Datetime.

And when i have made the migration, i have an error like this :
DateTime::__construct(): Argument #1 ($datetime) must be of type string, DateTime given

The Stack Trace :
> TypeError
> --
> TypeError: DateTime::__construct(): Argument #1 ($datetime) must be of type string, DateTime given    at vendor/symfony/http-kernel/Controller/ArgumentResolver/DateTimeValueResolver.php:70   at DateTime->__construct(object(DateTime))      (vendor/symfony/http-kernel/Controller/ArgumentResolver/DateTimeValueResolver.php:70)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php:58)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/http-kernel/Controller/ArgumentResolver.php:58)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(object(Request), array(object(LogController), 'logStatisticsAction'))      (vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php:38)   at Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(object(Request), array(object(LogController), 'logStatisticsAction'))      (vendor/symfony/http-kernel/HttpKernel.php:144)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/http-kernel/HttpKernel.php:74)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:17)
>

**Comment by mbabker** [comment]
IMO, symfony/symfony#46199 is probably the most practical fix for upgrading users short of completely disabling the param converters from this bundle.
