### ISSUE TITLE
DoctrineParamConverter to use POST parameters

### ISSUE THREAD

**Issue by dhirtzbruch** [sensiolabs/SensioFrameworkExtraBundle#773]
I looked both through the docs and did some googling, however I was not able to find any solution not involving custom ParamConverters. However, please bear with me if I did overlook anything.

I got a post form and would like to automagically load an entity from Doctrine - same behavior as in the current DoctrineParamConverter, but using a post parameter instead of a route attribute.

I thought there might be a reason loading parameters from the post request is not (yet) included in the current bundle. Is there any? Otherwise, I'd appreciate to provide a PR adding that functionality. I thought we could approach this by adding a new option `post = false` to the DoctrineParamConverter. Setting default to `false` should not result in any BC breaks / unexpected behaviour.

Any thoughts on this?

**Comment by derrabus** [comment]
Hey. We are planning to sunset this bundle, see symfony/symfony#44705. Features like this should either be implemented in userland or Symfony's core.

**Comment by dhirtzbruch** [comment]
Oh, didn't know that - thank you. I implemented a workaround in our code base for the time being.
